[phases.setup]
nixPkgs = ["nodejs_20", "python3", "gcc", "gnumake"]
aptPkgs = [
  "bzip2",
  "libcairo2-dev",
  "libjpeg-dev",
  "libpango1.0-dev",
  "libgif-dev",
  "openssl",
  "libssl-dev",
  "build-essential",
  "pkg-config"
]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = [
  "npx prisma generate",
  "npm run build"
]

[start]
cmd = "npm run deploy && node dist/main"
