/**
 * GitHub Repo Service - GitHub 仓库操作服务
 *
 * 创建仓库、推送代码、管理分支和 PR
 */

import { Injectable, Logger, NotFoundException } from "@nestjs/common";
import { PrismaService } from "../../../../common/prisma/prisma.service";
import { GithubOAuthService } from "./github-oauth.service";
import { Octokit } from "@octokit/rest";
import { AiCodingPRState } from "@prisma/client";

export interface CreateRepoDto {
  name: string;
  description?: string;
  isPrivate?: boolean;
}

export interface PushToRepoDto {
  branch?: string;
  commitMessage?: string;
}

export interface CreateBranchDto {
  branchName: string;
  baseBranch?: string;
}

export interface CreatePRDto {
  title: string;
  body?: string;
  headBranch: string;
  baseBranch?: string;
  iterationId?: string;
}

@Injectable()
export class GithubRepoService {
  private readonly logger = new Logger(GithubRepoService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly githubOAuth: GithubOAuthService,
  ) {}

  /**
   * 获取已认证的 Octokit 实例
   */
  private async getOctokit(userId: string): Promise<Octokit> {
    const token = await this.githubOAuth.getAccessToken(userId);
    return new Octokit({ auth: token });
  }

  /**
   * 为项目创建新的 GitHub 仓库
   */
  async createRepository(
    projectId: string,
    userId: string,
    dto: CreateRepoDto,
  ) {
    this.logger.log(`Creating GitHub repository for project ${projectId}`);

    const octokit = await this.getOctokit(userId);
    const connection = await this.githubOAuth.getConnection(userId);

    if (!connection) {
      throw new NotFoundException("GitHub not connected");
    }

    // 检查项目是否存在
    const project = await this.prisma.aiCodingProject.findFirst({
      where: { id: projectId, userId },
    });

    if (!project) {
      throw new NotFoundException("Project not found");
    }

    // 检查是否已经关联仓库
    const existingRepo = await this.prisma.aiCodingGithubRepo.findUnique({
      where: { projectId },
    });

    if (existingRepo) {
      throw new Error("Project already has a GitHub repository linked");
    }

    // 创建仓库
    const { data: repo } = await octokit.repos.createForAuthenticatedUser({
      name: dto.name,
      description: dto.description || `Generated by DeepDive AI Coding`,
      private: dto.isPrivate ?? true,
      auto_init: true,
    });

    // 保存仓库链接
    const githubRepo = await this.prisma.aiCodingGithubRepo.create({
      data: {
        projectId,
        owner: repo.owner.login,
        repo: repo.name,
        fullName: repo.full_name,
        htmlUrl: repo.html_url,
        cloneUrl: repo.clone_url,
        defaultBranch: repo.default_branch || "main",
        isPrivate: repo.private,
      },
    });

    // 更新项目的 GitHub 信息
    await this.prisma.aiCodingProject.update({
      where: { id: projectId },
      data: {
        githubRepo: repo.full_name,
        githubUrl: repo.html_url,
      },
    });

    this.logger.log(`Created repository: ${repo.full_name}`);

    return githubRepo;
  }

  /**
   * 推送项目文件到 GitHub
   */
  async pushToRepository(
    projectId: string,
    userId: string,
    dto?: PushToRepoDto,
  ) {
    this.logger.log(`Pushing to GitHub for project ${projectId}`);

    const octokit = await this.getOctokit(userId);

    // 获取项目和文件
    const project = await this.prisma.aiCodingProject.findFirst({
      where: { id: projectId, userId },
      include: {
        files: {
          where: { version: undefined }, // 获取当前版本的文件
        },
        documents: true,
      },
    });

    if (!project) {
      throw new NotFoundException("Project not found");
    }

    // 获取当前版本的文件
    const currentVersionFiles = await this.prisma.aiCodingFile.findMany({
      where: {
        projectId,
        version: project.currentVersion,
      },
    });

    const githubRepo = await this.prisma.aiCodingGithubRepo.findUnique({
      where: { projectId },
    });

    if (!githubRepo) {
      throw new NotFoundException("GitHub repository not linked");
    }

    const branch = dto?.branch || githubRepo.defaultBranch;
    const commitMessage =
      dto?.commitMessage || `AI Coding update - v${project.currentVersion}`;

    // 获取当前分支的最新 commit SHA
    const { data: ref } = await octokit.git.getRef({
      owner: githubRepo.owner,
      repo: githubRepo.repo,
      ref: `heads/${branch}`,
    });

    const latestCommitSha = ref.object.sha;

    // 获取最新 commit 的 tree
    const { data: commit } = await octokit.git.getCommit({
      owner: githubRepo.owner,
      repo: githubRepo.repo,
      commit_sha: latestCommitSha,
    });

    const baseTreeSha = commit.tree.sha;

    // 为所有文件创建 blob
    const treeItems: Array<{
      path: string;
      mode: "100644";
      type: "blob";
      sha: string;
    }> = [];

    // 添加代码文件
    for (const file of currentVersionFiles) {
      const { data: blob } = await octokit.git.createBlob({
        owner: githubRepo.owner,
        repo: githubRepo.repo,
        content: Buffer.from(file.content).toString("base64"),
        encoding: "base64",
      });
      treeItems.push({
        path: file.path,
        mode: "100644",
        type: "blob",
        sha: blob.sha,
      });
    }

    // 添加文档文件
    for (const doc of project.documents) {
      const docPath = this.getDocumentPath(doc.type);
      const { data: blob } = await octokit.git.createBlob({
        owner: githubRepo.owner,
        repo: githubRepo.repo,
        content: Buffer.from(doc.content).toString("base64"),
        encoding: "base64",
      });
      treeItems.push({
        path: docPath,
        mode: "100644",
        type: "blob",
        sha: blob.sha,
      });
    }

    // 创建新 tree
    const { data: tree } = await octokit.git.createTree({
      owner: githubRepo.owner,
      repo: githubRepo.repo,
      base_tree: baseTreeSha,
      tree: treeItems,
    });

    // 创建 commit
    const { data: newCommit } = await octokit.git.createCommit({
      owner: githubRepo.owner,
      repo: githubRepo.repo,
      message: commitMessage,
      tree: tree.sha,
      parents: [latestCommitSha],
    });

    // 更新分支引用
    await octokit.git.updateRef({
      owner: githubRepo.owner,
      repo: githubRepo.repo,
      ref: `heads/${branch}`,
      sha: newCommit.sha,
    });

    // 更新推送状态
    await this.prisma.aiCodingGithubRepo.update({
      where: { id: githubRepo.id },
      data: {
        lastPushAt: new Date(),
        lastPushCommit: newCommit.sha,
      },
    });

    this.logger.log(`Pushed to ${githubRepo.fullName}: ${newCommit.sha}`);

    return {
      commitSha: newCommit.sha,
      commitUrl: `${githubRepo.htmlUrl}/commit/${newCommit.sha}`,
      filesCount: treeItems.length,
    };
  }

  /**
   * 创建新分支
   */
  async createBranch(projectId: string, userId: string, dto: CreateBranchDto) {
    this.logger.log(
      `Creating branch ${dto.branchName} for project ${projectId}`,
    );

    const octokit = await this.getOctokit(userId);

    const githubRepo = await this.prisma.aiCodingGithubRepo.findUnique({
      where: { projectId },
    });

    if (!githubRepo) {
      throw new NotFoundException("GitHub repository not linked");
    }

    // 获取基础分支的 SHA
    const baseBranch = dto.baseBranch || githubRepo.defaultBranch;
    const { data: ref } = await octokit.git.getRef({
      owner: githubRepo.owner,
      repo: githubRepo.repo,
      ref: `heads/${baseBranch}`,
    });

    // 创建新分支
    await octokit.git.createRef({
      owner: githubRepo.owner,
      repo: githubRepo.repo,
      ref: `refs/heads/${dto.branchName}`,
      sha: ref.object.sha,
    });

    this.logger.log(`Created branch: ${dto.branchName}`);

    return {
      branch: dto.branchName,
      baseBranch,
      sha: ref.object.sha,
    };
  }

  /**
   * 创建 Pull Request
   */
  async createPullRequest(projectId: string, userId: string, dto: CreatePRDto) {
    this.logger.log(`Creating PR for project ${projectId}`);

    const octokit = await this.getOctokit(userId);

    const githubRepo = await this.prisma.aiCodingGithubRepo.findUnique({
      where: { projectId },
    });

    if (!githubRepo) {
      throw new NotFoundException("GitHub repository not linked");
    }

    const baseBranch = dto.baseBranch || githubRepo.defaultBranch;

    // 创建 PR
    const { data: pr } = await octokit.pulls.create({
      owner: githubRepo.owner,
      repo: githubRepo.repo,
      title: dto.title,
      body: dto.body || "Changes generated by DeepDive AI Coding",
      head: dto.headBranch,
      base: baseBranch,
    });

    // 保存 PR 记录
    const prRecord = await this.prisma.aiCodingPullRequest.create({
      data: {
        githubRepoId: githubRepo.id,
        iterationId: dto.iterationId,
        prNumber: pr.number,
        title: pr.title,
        body: pr.body,
        headBranch: dto.headBranch,
        baseBranch,
        htmlUrl: pr.html_url,
        state: AiCodingPRState.OPEN,
      },
    });

    this.logger.log(`Created PR #${pr.number}: ${pr.html_url}`);

    return prRecord;
  }

  /**
   * 获取项目的 Pull Requests
   */
  async getPullRequests(projectId: string, userId: string) {
    const project = await this.prisma.aiCodingProject.findFirst({
      where: { id: projectId, userId },
    });

    if (!project) {
      throw new NotFoundException("Project not found");
    }

    const githubRepo = await this.prisma.aiCodingGithubRepo.findUnique({
      where: { projectId },
      include: {
        pullRequests: {
          orderBy: { createdAt: "desc" },
        },
      },
    });

    return githubRepo?.pullRequests || [];
  }

  /**
   * 获取项目的 GitHub 仓库信息
   */
  async getRepoInfo(projectId: string, userId: string) {
    const project = await this.prisma.aiCodingProject.findFirst({
      where: { id: projectId, userId },
    });

    if (!project) {
      throw new NotFoundException("Project not found");
    }

    return this.prisma.aiCodingGithubRepo.findUnique({
      where: { projectId },
      include: {
        pullRequests: {
          take: 5,
          orderBy: { createdAt: "desc" },
        },
      },
    });
  }

  /**
   * 同步 PR 状态
   */
  async syncPRStatus(projectId: string, userId: string) {
    const octokit = await this.getOctokit(userId);

    const githubRepo = await this.prisma.aiCodingGithubRepo.findUnique({
      where: { projectId },
      include: { pullRequests: true },
    });

    if (!githubRepo) {
      return;
    }

    for (const pr of githubRepo.pullRequests) {
      try {
        const { data: ghPR } = await octokit.pulls.get({
          owner: githubRepo.owner,
          repo: githubRepo.repo,
          pull_number: pr.prNumber,
        });

        const state = ghPR.merged_at
          ? AiCodingPRState.MERGED
          : ghPR.closed_at
            ? AiCodingPRState.CLOSED
            : AiCodingPRState.OPEN;

        await this.prisma.aiCodingPullRequest.update({
          where: { id: pr.id },
          data: {
            state,
            mergedAt: ghPR.merged_at ? new Date(ghPR.merged_at) : null,
            closedAt: ghPR.closed_at ? new Date(ghPR.closed_at) : null,
          },
        });
      } catch {
        // 忽略单个 PR 同步失败
      }
    }
  }

  /**
   * 获取文档路径
   */
  private getDocumentPath(type: string): string {
    switch (type) {
      case "PRD":
        return "docs/PRD.md";
      case "DESIGN":
        return "docs/DESIGN.md";
      case "API":
        return "docs/API.md";
      case "README":
        return "README.md";
      case "CHANGELOG":
        return "CHANGELOG.md";
      default:
        return `docs/${type.toLowerCase()}.md`;
    }
  }
}
