/**
 * Research Leader Service
 *
 * Leader 驱动的研究协调服务
 * 负责：任务理解、维度规划、Agent 分配、质量审核、报告整合
 */

import {
  Injectable,
  Logger,
  NotFoundException,
  ServiceUnavailableException,
  InternalServerErrorException,
} from "@nestjs/common";
import { PrismaService } from "@/common/prisma/prisma.service";
import {
  ChatFacade,
  AgentFacade,
  ToolFacade,
  UserIntent,
} from "@/modules/ai-engine/facade";
import {
  LeaderDecisionType,
  ResearchTaskStatus,
  AIModelType,
} from "@prisma/client";
import { ResearchEventEmitterService } from "./research-event-emitter.service";
import { sanitize } from "../../utils/prompt-sanitizer";
import { extractJsonFromAIResponse } from "@/common/utils/json-extraction.utils";
import { toPrismaJson } from "@/common/utils/prisma-json.utils";
import {
  LeaderToolService,
  LeaderActionType,
  LeaderActionResult,
} from "../data/leader-tool.service";
import { TASK_PRIORITY } from "../../types/mission.types";
import {
  LEADER_PLAN_PROMPT,
  LEADER_REVIEW_PROMPT,
  GLOBAL_OUTLINE_PROMPT,
  DIMENSION_OUTLINE_PROMPT,
  LEADER_DECODE_PROMPT,
  LEADER_INTERVENE_PROMPT,
  getLanguageInstruction,
} from "../../prompts";
import {
  ANALYSIS_SKILL_DEFINITIONS,
  type LeaderPlan,
  type LeaderPlannedDimension,
  type AgentAssignment,
  type ReviewDecision,
  type DimensionIntentUnderstanding,
  type AnalysisSkill,
  type AgentSectionConfig,
  type AllocatedFigure,
  type SectionPlan,
  type DimensionOutline,
  type SectionReviewDecision,
  type IntegratedDimensionResult,
  type LeaderModelInfo,
  type GlobalOutline,
} from "../../types/leader.types";

// Re-export for backwards compatibility
export type {
  LeaderPlan,
  LeaderPlannedDimension,
  AgentAssignment,
  ReviewDecision,
  DimensionIntentUnderstanding,
  AnalysisSkill,
  AgentSectionConfig,
  AllocatedFigure,
  SectionPlan,
  DimensionOutline,
  SectionReviewDecision,
  IntegratedDimensionResult,
  LeaderModelInfo,
  GlobalOutline,
};
export { ANALYSIS_SKILL_DEFINITIONS };

/**
 * Whitelist of valid skill names (kebab-case, matching file names in topic-insights/skills/).
 * Used to filter out non-existent skill names generated by the LLM.
 */
const VALID_SKILLS = new Set([
  "cause-effect",
  "claim-extraction",
  "comparison",
  "competitive-analysis",
  "consistency-check",
  "content-critique",
  "content-refine",
  "critical-thinking",
  "data-interpretation",
  "debate-argument-generator",
  "debate-judge-assessor",
  "debate-verdict-synthesizer",
  "dedup-checker",
  "deep-dive",
  "dimension-research",
  "dimension-review",
  "dimension-synthesizer",
  "entity-extraction",
  "fact-check",
  "fact-verification",
  "future-projection",
  "hypothesis-verification",
  "multi-path-reasoning",
  "multi-view-synthesizer",
  "plan-adjuster",
  "rag-fusion-query",
  "report-editing",
  "report-synthesis",
  "research-planning",
  "section-review",
  "specialized-role-analysis",
  "swot-analysis",
  "synthesis",
  "task-quality-evaluator",
  "trend-analysis",
]);

// ==================== Service ====================

@Injectable()
export class ResearchLeaderService {
  private readonly logger = new Logger(ResearchLeaderService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly chatFacade: ChatFacade,
    private readonly agentFacade: AgentFacade,
    private readonly toolFacade: ToolFacade,
    private readonly eventEmitter: ResearchEventEmitterService,
    private readonly leaderToolService: LeaderToolService,
  ) {}

  /**
   * 获取推理模型信息
   * ★ 委托给 AIEngineFacade 处理模型选择逻辑
   */
  async getReasoningModel(): Promise<LeaderModelInfo | null> {
    this.logger.debug("[getReasoningModel] Starting model selection");

    const allModels = await this.chatFacade.getAvailableModelsExtended();
    this.logger.debug(
      `[getReasoningModel] Found ${allModels.length} available models`,
    );

    // 使用 AIEngineFacade 的能力获取推理模型
    const modelInfo = await this.chatFacade.getReasoningModel();

    if (!modelInfo) {
      this.logger.error("[getReasoningModel] AI Engine returned no model");
      return null;
    }

    this.logger.log(
      `[getReasoningModel] AI Engine selected: ${modelInfo.id} (${modelInfo.provider}, isReasoning: ${modelInfo.isReasoning})`,
    );

    // 警告：如果选择的不是推理模型
    if (!modelInfo.isReasoning) {
      this.logger.warn(
        `[getReasoningModel] Selected model ${modelInfo.id} is not a reasoning model, fallback occurred`,
      );
    }

    return {
      modelId: modelInfo.id,
      modelName: modelInfo.name,
      provider: modelInfo.provider,
      isReasoning: modelInfo.isReasoning ?? false,
    };
  }

  /**
   * Leader 规划研究任务
   * 分析用户需求，自主决定维度和执行策略
   */
  async planResearch(
    topicId: string,
    userPrompt?: string,
  ): Promise<LeaderPlan> {
    this.logger.log(`[planResearch] Starting planning for topic ${topicId}`);

    // 1. 获取专题信息
    const topic = await this.prisma.researchTopic.findUnique({
      where: { id: topicId },
      include: { dimensions: true },
    });

    if (!topic) {
      throw new NotFoundException(`Topic ${topicId} not found`);
    }

    // 2. 获取推理模型
    const leaderModel = await this.getReasoningModel();
    if (!leaderModel) {
      throw new ServiceUnavailableException(
        "No reasoning model available for Leader",
      );
    }

    // 3. 获取可用的 CHAT 模型列表（供 Leader 为 Agent 分配）
    const availableModels = await this.chatFacade.getAvailableModelsExtended();
    // ★ 过滤不可用模型（如 API key 过期、熔断器打开），并对重复 modelId 去重
    const reachableModels = availableModels.filter(
      (m) => m.isAvailable !== false,
    );
    const uniqueModels = reachableModels.filter(
      (m, i, arr) => arr.findIndex((x) => x.id === m.id) === i,
    );
    if (reachableModels.length < availableModels.length) {
      this.logger.warn(
        `[planResearch] Filtered out ${availableModels.length - reachableModels.length} unavailable models`,
      );
    }

    // ★ 构建模型名称到真实 modelId 的映射（供后处理还原）
    // 当 displayName 与 modelId 不同时（如 ep-xxx 接入点），用 displayName 作为 prompt 展示名
    const modelNameToIdMap = new Map<string, string>();
    const nameCountMap = new Map<string, number>();
    const uniqueModelsForPrompt = uniqueModels.map((m) => {
      let promptName = m.name !== m.id ? m.name : m.id;

      // ★ 处理同名模型（如多个 Doubao 接入点），用能力类型区分
      const nameKey = promptName.toLowerCase();
      const count = nameCountMap.get(nameKey) || 0;
      nameCountMap.set(nameKey, count + 1);
      if (count > 0) {
        const suffix = m.isReasoning ? "reasoning" : `variant-${count + 1}`;
        promptName = `${promptName} (${suffix})`;
      }

      modelNameToIdMap.set(promptName.toLowerCase(), m.id);
      // 同时映射原始 id，以兼容 AI 直接使用 id 的情况
      modelNameToIdMap.set(m.id.toLowerCase(), m.id);
      return { ...m, promptName };
    });

    const availableModelsText =
      uniqueModelsForPrompt.length > 0
        ? uniqueModelsForPrompt
            .map((m) => `- ${m.promptName}（${m.provider}）`)
            .join("\n")
        : "- 使用默认模型";
    this.logger.log(
      `[planResearch] Available models for agents: ${uniqueModelsForPrompt.map((m) => m.promptName).join(", ")} (${availableModels.length} total, ${uniqueModels.length} unique)`,
    );

    // 4. 构建已有维度信息
    let existingDimensionsText = "无已有维度（首次研究）";
    if (topic.dimensions && topic.dimensions.length > 0) {
      existingDimensionsText = topic.dimensions
        .map(
          (d, i) =>
            `${i + 1}. **${d.name}**\n   - 描述：${d.description || "无"}\n   - 状态：${d.status}\n   - 搜索词：${(d.searchQueries as string[])?.join("、") || "待设定"}`,
        )
        .join("\n");
    }

    // 5. 构建 prompt
    // ★ 获取当前日期和年份，确保搜索词使用正确的年份
    const now = new Date();
    const currentYear = now.getFullYear().toString();
    const currentDate = now.toISOString().split("T")[0]; // YYYY-MM-DD 格式

    // ★ Security: 对用户输入进行消毒，防止 Prompt Injection
    const sanitizedUserPrompt = sanitize(userPrompt || "请进行全面研究");

    const prompt = LEADER_PLAN_PROMPT.replace("{topic}", topic.name)
      .replace("{topicType}", topic.type)
      .replace("{description}", topic.description || "无")
      .replace("{userPrompt}", sanitizedUserPrompt)
      .replace("{availableModels}", availableModelsText)
      .replace("{existingDimensions}", existingDimensionsText)
      .replace(/{currentDate}/g, currentDate)
      .replace(/{currentYear}/g, currentYear)
      .replace(
        "{languageInstruction}",
        getLanguageInstruction(topic.language || "zh"),
      );

    // 6. 调用 AI 获取规划
    const startTime = Date.now();
    let response;
    try {
      response = await this.chatFacade.chat({
        messages: [
          {
            role: "system",
            content: "你是专业的研究协调专家，请输出 JSON 格式的研究规划。",
          },
          { role: "user", content: prompt },
        ],
        model: leaderModel.modelId,
        skipGuardrails: true, // 内部系统调用，非用户输入
        taskProfile: {
          creativity: "medium",
          outputLength: "extended",
        },
        responseFormat: "json",
      });
    } catch (aiError) {
      this.logger.error(
        `[planResearch] AI call failed: ${aiError instanceof Error ? aiError.message : aiError}`,
      );
      throw new InternalServerErrorException(
        `AI 调用失败: ${aiError instanceof Error ? aiError.message : "未知错误"}`,
      );
    }
    const latencyMs = Date.now() - startTime;

    // 6. 验证响应
    if (!response?.content) {
      this.logger.error("[planResearch] AI returned empty response");
      throw new InternalServerErrorException("AI 返回空响应，请稍后重试");
    }

    this.logger.log(
      `[planResearch] AI response received in ${latencyMs}ms, length: ${response.content.length}`,
    );

    // 7. 解析响应
    const plan = this.extractJsonFromResponse<LeaderPlan>(
      response.content,
      "dimensions", // requiredKey for validation
    );

    if (!plan) {
      this.logger.error(
        `[planResearch] Failed to parse Leader plan. Response preview: ${response.content.slice(0, 500)}`,
      );
      throw new InternalServerErrorException(
        "无法解析 AI 规划响应，请稍后重试",
      );
    }

    // ★ 后处理：确保每个 Agent 都有 modelId、skills、tools
    if (plan.agentAssignments) {
      let modelIndex = 0;

      for (const assignment of plan.agentAssignments) {
        // 0. ★ 将 AI 填写的 displayName 还原为真实 modelId
        if (assignment.modelId) {
          const aiModelId = assignment.modelId.toLowerCase();
          let realId = modelNameToIdMap.get(aiModelId);

          // ★ 模糊匹配：AI 可能返回不完整的名称（如 "Doubao" 而非 "Doubao (豆包)"）
          // 选择最长前缀匹配，避免 "gpt" 误匹配到 "gpt-4o" 而非 "gpt-5.1"
          if (!realId) {
            let bestMatchLen = 0;
            for (const [key, id] of modelNameToIdMap.entries()) {
              if (key.startsWith(aiModelId) || aiModelId.startsWith(key)) {
                const matchLen = Math.min(key.length, aiModelId.length);
                if (matchLen > bestMatchLen) {
                  bestMatchLen = matchLen;
                  realId = id;
                }
              }
            }
          }

          if (realId && realId !== assignment.modelId) {
            this.logger.log(
              `[planResearch] Resolved model name "${assignment.modelId}" → "${realId}" for ${assignment.agentName || assignment.agentId}`,
            );
            assignment.modelId = realId;
          }
        }

        // 0.5. ★ 过滤掉不存在的 skill 名称（LLM 可能生成白名单外的 skill）
        if (assignment.skills && assignment.skills.length > 0) {
          const normalizedSkills = assignment.skills.map((s: string) =>
            s.replace(/_/g, "-").toLowerCase(),
          );
          const validSkills = normalizedSkills.filter((s: string) =>
            VALID_SKILLS.has(s),
          );
          const invalidSkills = normalizedSkills.filter(
            (s: string) => !VALID_SKILLS.has(s),
          );
          if (invalidSkills.length > 0) {
            this.logger.warn(
              `[planResearch] Filtered out invalid skills for ${assignment.agentName || assignment.agentId}: ${invalidSkills.join(", ")}`,
            );
          }
          assignment.skills = validSkills;
        }

        // 1. 为缺少 modelId 的 Agent 自动轮询分配
        if (!assignment.modelId && availableModels.length > 0) {
          const model = availableModels[modelIndex % availableModels.length];
          assignment.modelId = model.id;
          this.logger.log(
            `[planResearch] Auto-assigned model ${model.id} to ${assignment.agentName || assignment.agentId}`,
          );
          modelIndex++;
        }

        // 2. 为研究员确保有 skills（若 AI 未返回则根据维度内容智能选择）
        if (assignment.agentType === "dimension_researcher") {
          if (!assignment.skills || assignment.skills.length === 0) {
            assignment.skills = this.selectDefaultSkillsForDimension(
              assignment,
              plan.dimensions,
            );
            this.logger.debug(
              `[planResearch] Auto-assigned skills [${assignment.skills.join(", ")}] to ${assignment.agentName || assignment.agentId}`,
            );
          }
          if (!assignment.tools || assignment.tools.length === 0) {
            assignment.tools = ["web-search"];
            this.logger.debug(
              `[planResearch] Auto-assigned default tools to ${assignment.agentName || assignment.agentId}`,
            );
          }
          // ★ 为研究员确保有 assignmentReason（包括 modelReason）
          const dimensionNames =
            assignment.assignedDimensions
              ?.map((dimId) => {
                const dim = plan.dimensions.find((d) => d.id === dimId);
                return dim?.name || dimId;
              })
              .join("、") || "相关领域";

          if (!assignment.assignmentReason) {
            assignment.assignmentReason = {
              agentReason: `${assignment.agentName || "研究员"}专注于「${dimensionNames}」领域的深度调研，具备该领域的信息收集和分析能力`,
              modelReason: assignment.modelId
                ? `选择 ${assignment.modelId} 模型，因为其具备出色的信息检索、内容分析和逻辑推理能力`
                : "使用擅长信息检索和内容分析的模型",
            };
            this.logger.debug(
              `[planResearch] Auto-assigned default assignmentReason to ${assignment.agentName || assignment.agentId}`,
            );
          } else {
            // ★ 确保 agentReason 不为空
            if (!assignment.assignmentReason.agentReason) {
              assignment.assignmentReason.agentReason = `${assignment.agentName || "研究员"}专注于「${dimensionNames}」领域的深度调研`;
            }
          }
          // ★ 强制用具体模型信息覆盖 AI 返回的通用 modelReason
          if (assignment.modelId) {
            assignment.assignmentReason.modelReason = `选择 ${assignment.modelId} 模型，因为其具备出色的信息检索、内容分析和逻辑推理能力`;
          }
        }

        // 3. 为质量审核员确保有 skills
        if (assignment.agentType === "quality_reviewer") {
          if (!assignment.skills || assignment.skills.length === 0) {
            assignment.skills = ["critical-thinking", "synthesis"];
          }
          // ★ 为审核员确保有 assignmentReason
          if (!assignment.assignmentReason) {
            assignment.assignmentReason = {
              agentReason: `${assignment.agentName || "质量审核员"}负责全面审核研究成果，确保内容准确性、逻辑一致性和完整性`,
              modelReason: "使用擅长一致性检查和质量评估的模型",
            };
          } else if (!assignment.assignmentReason.agentReason) {
            assignment.assignmentReason.agentReason = `${assignment.agentName || "质量审核员"}负责全面审核研究成果，确保内容准确性、逻辑一致性和完整性`;
          }
          // ★ 强制用具体模型信息覆盖 AI 返回的通用 modelReason
          if (assignment.modelId) {
            assignment.assignmentReason.modelReason = `选择 ${assignment.modelId} 模型，因为其擅长一致性检查、事实核验和质量评估`;
          }
        }

        // 4. 为报告撰写员确保有 skills
        if (assignment.agentType === "report_writer") {
          if (!assignment.skills || assignment.skills.length === 0) {
            assignment.skills = ["synthesis"];
          }
          // ★ 为撰写员确保有 assignmentReason
          if (!assignment.assignmentReason) {
            assignment.assignmentReason = {
              agentReason: `${assignment.agentName || "报告撰写员"}负责整合多维度研究成果，生成结构清晰、逻辑连贯的专业报告`,
              modelReason: "使用具有强大语言生成和内容整合能力的模型",
            };
          } else if (!assignment.assignmentReason.agentReason) {
            assignment.assignmentReason.agentReason = `${assignment.agentName || "报告撰写员"}负责整合多维度研究成果，生成结构清晰、逻辑连贯的专业报告`;
          }
          // ★ 强制用具体模型信息覆盖 AI 返回的通用 modelReason
          if (assignment.modelId) {
            assignment.assignmentReason.modelReason = `选择 ${assignment.modelId} 模型，因为其具备强大的语言生成、内容整合和篇章组织能力`;
          }
        }
      }
    }

    this.logger.log(
      `[planResearch] Plan created with ${plan.dimensions.length} dimensions in ${latencyMs}ms`,
    );

    // ★ 打印 Agent 分配情况（包含模型、技能、工具）
    const researcherSummary = plan.agentAssignments
      ?.filter((a) => a.agentType === "dimension_researcher")
      .map((a) => {
        const parts = [a.agentName || a.agentId];
        if (a.modelId) parts.push(`model=${a.modelId}`);
        if (a.skills?.length) parts.push(`skills=[${a.skills.join(",")}]`);
        if (a.tools?.length) parts.push(`tools=[${a.tools.join(",")}]`);
        return parts.join(" ");
      })
      .join(" | ");
    this.logger.log(`[planResearch] Agent assignments: ${researcherSummary}`);

    return plan;
  }

  /**
   * Leader 审核任务结果
   */
  async reviewTaskResult(
    missionId: string,
    taskId: string,
    result: string | Record<string, unknown>,
    dimensionName?: string,
  ): Promise<ReviewDecision> {
    this.logger.log(`[reviewTaskResult] Reviewing task ${taskId}`);

    // 获取推理模型
    const leaderModel = await this.getReasoningModel();
    if (!leaderModel) {
      throw new ServiceUnavailableException(
        "No reasoning model available for Leader",
      );
    }

    // 构建 prompt
    const prompt = LEADER_REVIEW_PROMPT.replace(
      "{taskType}",
      "dimension_research",
    )
      .replace("{dimensionName}", dimensionName || "未知")
      .replace("{result}", JSON.stringify(result, null, 2));

    // 调用 AI 审核
    const startTime = Date.now();
    let response;
    try {
      response = await this.chatFacade.chat({
        messages: [
          {
            role: "system",
            content: "你是研究质量审核专家，请输出 JSON 格式的审核决策。",
          },
          { role: "user", content: prompt },
        ],
        model: leaderModel.modelId,
        skipGuardrails: true, // 内部系统调用，非用户输入
        taskProfile: {
          creativity: "low",
          outputLength: "medium",
        },
      });
    } catch (reviewError) {
      this.logger.error(
        `[reviewTaskResult] AI call failed: ${reviewError instanceof Error ? reviewError.message : reviewError}`,
      );
      return {
        taskId,
        status: "approved",
        feedback: "审核失败（AI 调用异常，默认通过）",
      };
    }
    const latencyMs = Date.now() - startTime;

    // 解析审核结果
    const review = this.extractJsonFromResponse<{
      status: "approved" | "needs_revision" | "rejected";
      feedback?: string;
      suggestions?: string[];
      revisionInstructions?: string;
      revisionNeeded?: boolean;
    }>(response.content, "status"); // requiredKey for validation

    if (!review) {
      this.logger.warn(
        "[reviewTaskResult] Failed to parse review, defaulting to approved",
      );
      return {
        taskId,
        status: "approved",
        feedback: "审核通过（解析失败，默认通过）",
      };
    }

    // 记录决策
    await this.recordDecision(
      missionId,
      LeaderDecisionType.REVIEW,
      {
        taskId,
        dimensionName,
      },
      review,
      review.feedback || "",
      leaderModel.modelId,
      latencyMs,
    );

    return {
      taskId,
      status: review.status ?? "approved",
      feedback: review.feedback || "",
      suggestions: review.suggestions,
      revisionInstructions: review.revisionInstructions,
    };
  }

  /**
   * 处理用户的 @Leader 消息
   * ★ 使用 IntentDetectionService 预检测意图，优化简单请求的响应
   */
  async handleUserMessage(
    topicId: string,
    missionId: string,
    userMessage: string,
  ): Promise<{ response: string; actionResults?: LeaderActionResult[] }> {
    this.logger.log(
      `[handleUserMessage] Processing @Leader message for topic ${topicId}`,
    );

    // ★ Security: 对用户输入进行消毒，防止 Prompt Injection
    const sanitizedMessage = sanitize(userMessage);

    // ★ 保存用户消息到数据库（对话历史）
    await this.eventEmitter.saveUserMessage(
      topicId,
      missionId,
      sanitizedMessage,
    );

    // 0. 使用 AI Engine 的意图检测服务进行快速预检测
    if (!this.agentFacade.intentDetector) {
      this.logger.warn(
        "[handleUserMessage] intentDetector not available, skipping intent detection",
      );
      return { response: "意图检测服务不可用，请稍后重试" };
    }
    const intentResult =
      this.agentFacade.intentDetector.detectIntent(sanitizedMessage);
    this.logger.log(
      `[handleUserMessage] Intent detected: ${intentResult.intent} (confidence: ${intentResult.confidence})`,
    );

    // 1. 获取当前状态（包含 dimensions 用于显示当前维度列表）
    const mission = await this.prisma.researchMission.findUnique({
      where: { id: missionId },
      include: {
        topic: {
          include: {
            dimensions: true,
          },
        },
        tasks: true,
      },
    });

    if (!mission) {
      throw new NotFoundException(`Mission ${missionId} not found`);
    }

    // 2. 计算进度
    const completedTasks = mission.tasks.filter(
      (t) => t.status === "COMPLETED",
    );
    const inProgressTasks = mission.tasks.filter(
      (t) => t.status === "EXECUTING",
    );
    const progress =
      mission.tasks.length > 0
        ? Math.round((completedTasks.length / mission.tasks.length) * 100)
        : 0;

    // 3. 对于高置信度的简单意图，快速响应（无需调用推理模型）
    if (intentResult.confidence >= 0.75) {
      const quickResponse = this.handleQuickIntent(
        intentResult.intent,
        mission,
        progress,
        completedTasks.length,
        inProgressTasks.length,
      );
      if (quickResponse) {
        this.logger.log(
          `[handleUserMessage] Quick response for intent: ${intentResult.intent}`,
        );
        await this.recordDecision(
          missionId,
          LeaderDecisionType.INTERVENE,
          {
            userMessage: sanitizedMessage,
            detectedIntent: intentResult.intent,
          },
          { action: "quick_response" },
          quickResponse.response,
          "intent_detection_service",
          0,
        );
        // ★ 发射 WebSocket 事件到团队互动区
        await this.eventEmitter.emitLeaderResponse(
          topicId,
          missionId,
          quickResponse.response,
        );
        return quickResponse;
      }
    }

    // 4. 复杂意图：调用推理模型处理
    const leaderModel = await this.getReasoningModel();
    if (!leaderModel) {
      throw new ServiceUnavailableException(
        "No reasoning model available for Leader",
      );
    }

    // 5. 构建维度列表（供 Leader 了解当前有哪些维度）
    const dimensionList =
      mission.topic.dimensions && mission.topic.dimensions.length > 0
        ? mission.topic.dimensions
            .map((d, i) => `${i + 1}. ${d.name}（${d.status}）`)
            .join("\n")
        : "无维度";

    // 6. 构建 prompt（添加检测到的意图信息）
    const prompt = LEADER_INTERVENE_PROMPT.replace(
      "{topic}",
      mission.topic.name,
    )
      .replace("{progress}", String(progress))
      .replace("{stage}", mission.status)
      .replace(
        "{completedDimensions}",
        completedTasks
          .map((t) => t.dimensionName)
          .filter(Boolean)
          .join(", ") || "无",
      )
      .replace(
        "{inProgressDimensions}",
        inProgressTasks
          .map((t) => t.dimensionName)
          .filter(Boolean)
          .join(", ") || "无",
      )
      .replace("{dimensionList}", dimensionList)
      .replace("{userMessage}", sanitizedMessage);

    // 7. 调用 AI
    const startTime = Date.now();
    const response = await this.chatFacade.chat({
      messages: [
        {
          role: "system",
          content:
            "你是研究协调专家 Leader，请回应用户的指令并输出 JSON 格式的响应。",
        },
        { role: "user", content: prompt },
      ],
      model: leaderModel.modelId,
      skipGuardrails: true, // prompt 拼入系统生成的维度列表，可能触发误报
      taskProfile: {
        creativity: "medium",
        outputLength: "medium",
      },
    });
    const latencyMs = Date.now() - startTime;

    // 8. 解析响应
    const result = this.extractJsonFromResponse<{
      understanding?: string;
      actions?: Array<{
        type: string;
        params?: Record<string, unknown>;
      }>;
      response: string;
      planAdjustments?: unknown;
    }>(response.content, "response"); // requiredKey for validation

    if (!result) {
      const fallbackResponse = "收到您的指令，我会继续推进研究工作。";
      // ★ 发射 WebSocket 事件到团队互动区
      await this.eventEmitter.emitLeaderResponse(
        topicId,
        missionId,
        fallbackResponse,
      );
      return {
        response: fallbackResponse,
      };
    }

    // ★★★ 9. 执行 actions 数组中的动作 ★★★
    const actionResults: LeaderActionResult[] = [];
    if (result.actions && Array.isArray(result.actions)) {
      this.logger.log(
        `[handleUserMessage] Executing ${result.actions.length} actions`,
      );

      for (const action of result.actions) {
        const actionType = action.type as LeaderActionType;
        const params = action.params || {};

        this.logger.log(`[handleUserMessage] Executing action: ${actionType}`);

        try {
          let actionResult: LeaderActionResult;

          switch (actionType) {
            case LeaderActionType.CREATE_DIMENSION: {
              // 创建维度（拆分由 AI 根据用户明确意图决定，代码不强制拆分）
              actionResult = await this.leaderToolService.createDimension({
                topicId,
                name: params.name as string,
                description: params.description as string | undefined,
              });

              // ★ v8.2: 创建维度成功后，自动创建 ResearchTask 并恢复 Mission 执行
              if (actionResult.success && actionResult.data?.dimensionId) {
                const dimensionId = actionResult.data.dimensionId as string;
                const dimensionName = actionResult.data.name as string;

                try {
                  // 为新维度创建 ResearchTask
                  const sanitizedDimName = dimensionName
                    .replace(/[^a-zA-Z0-9\u4e00-\u9fa5]/g, "_")
                    .substring(0, 30);
                  const newAgentId = `researcher_${sanitizedDimName}_${Date.now()}`;

                  const task = await this.prisma.researchTask.create({
                    data: {
                      missionId,
                      title: `研究: ${dimensionName}`,
                      description:
                        (params.description as string) ||
                        `Leader 创建的新维度研究：${dimensionName}`,
                      taskType: "dimension_research",
                      dimensionName: dimensionName,
                      dimensionId: dimensionId,
                      assignedAgent: newAgentId,
                      assignedAgentType: "dimension_researcher",
                      priority: TASK_PRIORITY.DIMENSION_RESEARCH_DYNAMIC,
                      status: ResearchTaskStatus.PENDING,
                    },
                  });

                  // 更新 Mission 的 totalTasks 计数
                  await this.prisma.researchMission.update({
                    where: { id: missionId },
                    data: {
                      totalTasks: { increment: 1 },
                    },
                  });

                  // 更新质量审核任务的依赖
                  const qualityReviewTask =
                    await this.prisma.researchTask.findFirst({
                      where: {
                        missionId,
                        taskType: "quality_review",
                      },
                    });

                  if (qualityReviewTask) {
                    const currentDeps = qualityReviewTask.dependencies || [];
                    if (!currentDeps.includes(task.id)) {
                      await this.prisma.researchTask.update({
                        where: { id: qualityReviewTask.id },
                        data: {
                          dependencies: [...currentDeps, task.id],
                        },
                      });
                    }
                  }

                  this.logger.log(
                    `[handleUserMessage] Created ResearchTask ${task.id} for dimension "${dimensionName}"`,
                  );

                  // 触发 Mission 恢复执行（通过事件解耦，避免循环依赖）
                  this.eventEmitter.emitResumeMissionExecution(
                    missionId,
                    topicId,
                  );
                } catch (taskError) {
                  this.logger.error(
                    `[handleUserMessage] Failed to create ResearchTask: ${taskError}`,
                  );
                  // 不影响主流程，只记录错误
                }
              }
              break;
            }

            case LeaderActionType.DELETE_DIMENSION:
              actionResult = await this.leaderToolService.deleteDimension({
                topicId,
                dimensionName: params.dimensionName as string,
              });
              break;

            case LeaderActionType.CANCEL_TASK:
              actionResult = await this.leaderToolService.cancelTask({
                topicId,
                dimensionName: params.dimensionName as string | undefined,
                taskName: params.taskName as string | undefined,
              });
              break;

            case LeaderActionType.UPDATE_DIMENSION:
              actionResult = await this.leaderToolService.updateDimension({
                topicId,
                dimensionName: params.dimensionName as string,
                newName: params.newName as string | undefined,
                newDescription: params.newDescription as string | undefined,
              });
              break;

            case LeaderActionType.MERGE_DIMENSIONS:
              actionResult = await this.leaderToolService.mergeDimensions({
                topicId,
                sourceDimensionNames: params.sourceDimensionNames as string[],
                targetDimensionName: params.targetDimensionName as string,
              });
              break;

            case LeaderActionType.NO_ACTION:
              actionResult = {
                success: true,
                action: LeaderActionType.NO_ACTION,
                message: "无需执行动作",
              };
              break;

            default:
              this.logger.warn(
                `[handleUserMessage] Unknown action type: ${actionType}`,
              );
              actionResult = {
                success: false,
                action: actionType,
                message: `未知的动作类型: ${actionType}`,
              };
          }

          actionResults.push(actionResult);
          this.logger.log(
            `[handleUserMessage] Action result: ${actionResult.success ? "SUCCESS" : "FAILED"} - ${actionResult.message}`,
          );
        } catch (error) {
          this.logger.error(
            `[handleUserMessage] Action execution failed: ${error}`,
          );
          actionResults.push({
            success: false,
            action: actionType,
            message: `执行失败: ${error instanceof Error ? error.message : String(error)}`,
          });
        }
      }
    }

    // ★ Fix: 代码级别的删除意图检测和强制执行
    // 如果用户消息明确包含删除意图但 AI 没有输出 DELETE_DIMENSION action，强制执行
    const deleteKeywords = ["删除", "移除", "取消", "去掉", "不要"];
    const hasDeleteIntent = deleteKeywords.some((kw) =>
      sanitizedMessage.includes(kw),
    );
    const hasDeleteAction = actionResults.some(
      (r) => r.action === LeaderActionType.DELETE_DIMENSION,
    );

    if (hasDeleteIntent && !hasDeleteAction) {
      this.logger.warn(
        `[handleUserMessage] Detected delete intent but no DELETE_DIMENSION action, attempting fallback delete`,
      );

      // 尝试从消息中提取维度名称
      // 模式: "删除维度：X" / "删除 X 维度" / "把 X 删除" / "删除「X」"
      const dimensionPatterns = [
        /删除[维度章节]*[：:「\s]*([^」\s,，。]+)/,
        /移除[维度章节]*[：:「\s]*([^」\s,，。]+)/,
        /把[「\s]*([^」\s,，。]+)[」\s]*删除/,
        /不要[「\s]*([^」\s,，。]+)/,
        /取消[「\s]*([^」\s,，。]+)/,
      ];

      let extractedDimensionName: string | null = null;
      for (const pattern of dimensionPatterns) {
        const match = sanitizedMessage.match(pattern);
        if (match && match[1]) {
          extractedDimensionName = match[1].replace(/[「」]/g, "").trim();
          break;
        }
      }

      if (extractedDimensionName) {
        this.logger.log(
          `[handleUserMessage] Fallback: Attempting to delete dimension "${extractedDimensionName}"`,
        );

        try {
          const deleteResult = await this.leaderToolService.deleteDimension({
            topicId,
            dimensionName: extractedDimensionName,
          });
          actionResults.push(deleteResult);

          if (deleteResult.success) {
            this.logger.log(
              `[handleUserMessage] Fallback delete successful: ${deleteResult.message}`,
            );
            // 更新响应以反映删除操作
            result.response = deleteResult.message;
          }
        } catch (error) {
          this.logger.error(
            `[handleUserMessage] Fallback delete failed: ${error}`,
          );
        }
      } else {
        this.logger.warn(
          `[handleUserMessage] Could not extract dimension name from delete intent`,
        );
      }
    }

    // 10. 记录决策（包含动作执行结果）
    await this.recordDecision(
      missionId,
      LeaderDecisionType.INTERVENE,
      { userMessage: sanitizedMessage, detectedIntent: intentResult.intent },
      { ...result, actionResults },
      result.response,
      leaderModel.modelId,
      latencyMs,
    );

    // 11. 构建最终响应（如果有动作执行失败，附加错误信息）
    const failedActions = actionResults.filter((r) => !r.success);
    let finalResponse = result.response;
    if (failedActions.length > 0) {
      const errorMessages = failedActions.map((r) => r.message).join("; ");
      finalResponse += `\n\n⚠️ 部分操作未成功: ${errorMessages}`;
    }

    // ★ 发射 WebSocket 事件到团队互动区
    await this.eventEmitter.emitLeaderResponse(
      topicId,
      missionId,
      finalResponse,
    );

    return {
      response: finalResponse,
      actionResults,
    };
  }

  /**
   * V5 L3: 从章节内容中提取事实断言
   * 使用 CHAT_FAST 模型批量处理
   */
  async extractClaims(
    sectionId: string,
    sectionContent: string,
  ): Promise<import("../../types/v5-research.types").ExtractedClaim[]> {
    this.logger.log(
      `[extractClaims] Extracting claims from section ${sectionId}`,
    );

    const { CLAIM_EXTRACTION_PROMPT } =
      await import("../../prompts/v5-research.prompt");
    const prompt = CLAIM_EXTRACTION_PROMPT.replace(
      "{sectionContent}",
      sectionContent.substring(0, 4000),
    ).replace("{sectionId}", sectionId);

    try {
      const result = await this.chatFacade.chatStructured<{
        claims: import("../../types/v5-research.types").ExtractedClaim[];
      }>({
        messages: [{ role: "user", content: prompt }],
        systemPrompt: "你是事实核查专家，精确提取可验证的事实断言。",
        schema: {
          type: "object",
          properties: {
            claims: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  id: { type: "string" },
                  statement: { type: "string" },
                  sectionId: { type: "string" },
                  sourceEvidenceIndices: {
                    type: "array",
                    items: { type: "number" },
                  },
                  importance: {
                    type: "string",
                    enum: ["high", "medium", "low"],
                  },
                },
                required: [
                  "id",
                  "statement",
                  "sectionId",
                  "sourceEvidenceIndices",
                  "importance",
                ],
              },
            },
          },
          required: ["claims"],
        },
        modelType: AIModelType.CHAT_FAST,
        skipGuardrails: true,
        throwOnParseError: false,
        taskProfile: {
          creativity: "deterministic",
          outputLength: "medium",
        },
      });

      if (result.data?.claims) {
        this.logger.log(
          `[extractClaims] Extracted ${result.data.claims.length} claims from section ${sectionId}`,
        );
        return result.data.claims;
      }

      this.logger.warn(
        `[extractClaims] Failed to parse claims for section ${sectionId}. Raw (first 300 chars): ${result.rawContent?.slice(0, 300)}`,
      );
      return [];
    } catch (error) {
      this.logger.error(
        `[extractClaims] Error extracting claims for section ${sectionId}: ${error instanceof Error ? error.message : error}`,
      );
      return [];
    }
  }

  /**
   * V5 L3: 验证研究假设
   * 根据收集到的证据验证 L1 阶段提出的假设
   */
  async verifyHypotheses(
    hypotheses: import("../../types/v5-research.types").ResearchHypothesis[],
    evidenceSummary: string,
  ): Promise<
    import("../../types/v5-research.types").HypothesisVerificationResult[]
  > {
    if (hypotheses.length === 0) return [];

    this.logger.log(
      `[verifyHypotheses] Verifying ${hypotheses.length} hypotheses`,
    );

    const { HYPOTHESIS_VERIFICATION_PROMPT } =
      await import("../../prompts/v5-research.prompt");
    const prompt = HYPOTHESIS_VERIFICATION_PROMPT.replace(
      "{hypothesesJson}",
      JSON.stringify(hypotheses, null, 2),
    ).replace("{evidenceSummary}", evidenceSummary.substring(0, 6000));

    try {
      const result = await this.chatFacade.chatStructured<{
        results: import("../../types/v5-research.types").HypothesisVerificationResult[];
      }>({
        messages: [{ role: "user", content: prompt }],
        systemPrompt: "你是研究方法论专家，严谨验证研究假设。",
        schema: {
          type: "object",
          properties: {
            results: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  hypothesisId: { type: "string" },
                  status: {
                    type: "string",
                    enum: [
                      "supported",
                      "refuted",
                      "partially_supported",
                      "inconclusive",
                    ],
                  },
                  supportingEvidence: { type: "string" },
                  contradictingEvidence: { type: "string" },
                  confidence: { type: "number" },
                  refinedStatement: { type: "string" },
                },
                required: [
                  "hypothesisId",
                  "status",
                  "supportingEvidence",
                  "contradictingEvidence",
                  "confidence",
                ],
              },
            },
          },
          required: ["results"],
        },
        modelType: AIModelType.CHAT_FAST,
        skipGuardrails: true,
        throwOnParseError: false,
        taskProfile: {
          creativity: "low",
          outputLength: "medium",
        },
      });

      if (result.data?.results) {
        this.logger.log(
          `[verifyHypotheses] Verified ${result.data.results.length} hypotheses`,
        );
        return result.data.results;
      }

      this.logger.warn(
        `[verifyHypotheses] Failed to parse hypothesis verification results`,
      );
      return [];
    } catch (error) {
      this.logger.error(`[verifyHypotheses] Error: ${error}`);
      return [];
    }
  }

  /**
   * 快速处理简单意图（无需调用推理模型）
   * ★ 使用 IntentDetectionService 检测结果
   */
  private handleQuickIntent(
    intent: UserIntent,
    mission: { topic: { name: string }; status: string },
    progress: number,
    completedCount: number,
    inProgressCount: number,
  ): { response: string; actionResults?: LeaderActionResult[] } | null {
    switch (intent) {
      case UserIntent.CONTINUE:
        // 继续研究：返回当前进度并确认继续
        return {
          response: `好的，继续推进「${mission.topic.name}」的研究工作。当前进度：${progress}%，已完成 ${completedCount} 个维度，${inProgressCount} 个维度正在进行中。`,
        };

      case UserIntent.SUMMARIZE:
        // 总结请求：提供当前状态摘要（详细总结仍需调用AI）
        if (progress < 50) {
          return {
            response: `研究「${mission.topic.name}」进度 ${progress}%，目前还在收集资料阶段。已完成 ${completedCount} 个维度，${inProgressCount} 个正在进行。建议等待更多维度完成后再生成详细总结。`,
          };
        }
        // 进度较高时，需要详细总结，交给AI处理
        return null;

      case UserIntent.GENERAL_CHAT:
        // 一般聊天：简短友好回复
        return {
          response: `您好！我是负责「${mission.topic.name}」研究的 Leader。当前研究进度 ${progress}%。有什么我可以帮您的吗？`,
        };

      default:
        // 其他意图需要AI处理
        return null;
    }
  }

  // ==================== Leader 解码用户输入 ====================

  /**
   * ★ v8.1: 构建项目配置上下文
   * 让 Leader 了解当前项目的完整配置，包括：
   * - 知识库配置
   * - 可用工具列表（动态从 AI Engine 获取）
   * - 团队成员配置
   * - 搜索时间范围
   */
  private async buildProjectContext(
    topicId: string,
    missionId?: string,
  ): Promise<string> {
    try {
      // ★ 优化: 使用 Promise.all 并行查询，减少数据库往返
      const [topic, mission] = await Promise.all([
        // 1. 获取专题信息和配置
        this.prisma.researchTopic.findUnique({
          where: { id: topicId },
          include: { dimensions: true },
        }),
        // 2. 获取任务信息（如果有 missionId）
        missionId
          ? this.prisma.researchMission.findUnique({
              where: { id: missionId },
              select: { leaderPlan: true },
            })
          : Promise.resolve(null),
      ]);

      if (!topic) {
        return "## 项目配置\n暂无项目配置信息";
      }

      const topicConfig = (topic.topicConfig as Record<string, unknown>) || {};

      // 3. 获取知识库名称（如果配置了）
      let knowledgeBaseText = "未配置";
      const knowledgeBaseIds = topicConfig.knowledgeBaseIds as
        | string[]
        | undefined;
      if (
        Array.isArray(knowledgeBaseIds) &&
        knowledgeBaseIds.length > 0 &&
        knowledgeBaseIds.every((id) => typeof id === "string" && id.length > 0)
      ) {
        try {
          const knowledgeBases = await this.prisma.knowledgeBase.findMany({
            where: { id: { in: knowledgeBaseIds } },
            select: { id: true, name: true },
          });
          if (knowledgeBases.length > 0) {
            knowledgeBaseText = knowledgeBases
              .map((kb) => `「${kb.name}」`)
              .join(", ");
          }
        } catch (e) {
          this.logger.warn(
            `[buildProjectContext] Failed to fetch knowledge bases: ${e}`,
          );
        }
      }

      // 4. ★ 动态获取可用工具列表（从 AI Engine）- 添加空值防护
      const availableTools = this.toolFacade.getAvailableTools() || [];
      const toolsText =
        availableTools.length > 0
          ? availableTools
              .filter((t) => t && t.name) // 过滤无效工具
              .map(
                (t) =>
                  `- ${t.name}${t.description ? `: ${t.description}` : ""}`,
              )
              .join("\n")
          : "- 暂无可用工具";

      // 5. 获取搜索时间范围配置
      const searchTimeRange =
        (topicConfig.searchTimeRange as string) || "不限（搜索所有时间的内容）";

      // 6. 获取团队成员配置（从 LeaderPlan）
      let teamMembersText = "团队尚未组建";
      const leaderPlan = mission?.leaderPlan as LeaderPlan | null;
      if (
        leaderPlan?.agentAssignments &&
        leaderPlan.agentAssignments.length > 0
      ) {
        teamMembersText = leaderPlan.agentAssignments
          .map((a) => {
            const parts = [
              `- **${a.agentName || a.agentId}** (${a.agentType})`,
            ];
            if (a.modelId) parts.push(`  - 模型: ${a.modelId}`);
            if (a.skills?.length)
              parts.push(`  - 技能: ${a.skills.join(", ")}`);
            if (a.tools?.length) parts.push(`  - 工具: ${a.tools.join(", ")}`);
            if (a.role) parts.push(`  - 职责: ${a.role}`);
            return parts.join("\n");
          })
          .join("\n");
      }

      // 7. 获取研究维度列表
      const dimensionsText =
        topic.dimensions && topic.dimensions.length > 0
          ? topic.dimensions
              .map(
                (d, i) =>
                  `${i + 1}. ${d.name}${d.status === "COMPLETED" ? " ✓" : d.status === "RESEARCHING" ? " ⏳" : ""}`,
              )
              .join("\n")
          : "暂无研究维度";

      // 8. ★ 获取可用分析技能
      const skillsText = ANALYSIS_SKILL_DEFINITIONS.map(
        (s) => `- ${s.name}: ${s.description}`,
      ).join("\n");

      // 构建完整的项目配置上下文
      return `## 项目配置

### 知识库
${knowledgeBaseText}

### 搜索时间范围
${searchTimeRange}

### 可用研究工具
${toolsText}

### 可用分析技能
${skillsText}

### 研究维度
${dimensionsText}

### 研究团队
${teamMembersText}`;
    } catch (error) {
      this.logger.error(
        `[buildProjectContext] Failed to build context: ${error}`,
      );
      return "## 项目配置\n暂无项目配置信息";
    }
  }

  /**
   * Leader 解码响应类型
   */
  static readonly DecisionTypes = {
    DIRECT_ANSWER: "DIRECT_ANSWER",
    CREATE_TODO: "CREATE_TODO",
    CLARIFY: "CLARIFY",
    ACKNOWLEDGE: "ACKNOWLEDGE",
  } as const;

  /**
   * ★ Leader 解码用户输入
   * 类似 Claude Code CLI：先理解用户意图，再决定如何响应
   *
   * @param topicId 专题ID
   * @param userMessage 用户消息
   * @param missionId 可选的任务ID（如果已有进行中的任务）
   * @returns 解码结果，包含决策类型和响应
   */
  async decodeUserInput(
    topicId: string,
    userMessage: string,
    missionId?: string,
  ): Promise<{
    decisionType: "DIRECT_ANSWER" | "CREATE_TODO" | "CLARIFY" | "ACKNOWLEDGE";
    understanding: string;
    response: string;
    todoTitle?: string;
    todoDescription?: string;
    clarifyQuestion?: string;
    clarifyOptions?: string[];
  }> {
    // ★ Security: 对用户输入进行消毒，防止 Prompt Injection
    const sanitizedMessage = sanitize(userMessage);

    this.logger.log(
      `[decodeUserInput] Decoding user input for topic ${topicId}: "${sanitizedMessage.substring(0, 50)}..."`,
    );

    // 1. 获取专题信息
    const topic = await this.prisma.researchTopic.findUnique({
      where: { id: topicId },
      include: { dimensions: true },
    });

    if (!topic) {
      throw new NotFoundException(`Topic ${topicId} not found`);
    }

    // 2. 获取任务状态（如果有 missionId）
    let mission = null;
    let progress = 0;
    let completedDimensions: string[] = [];
    let inProgressDimensions: string[] = [];
    let todoList = "暂无任务";

    if (missionId) {
      mission = await this.prisma.researchMission.findUnique({
        where: { id: missionId },
        include: { tasks: true },
      });

      if (mission) {
        const completedTasks = mission.tasks.filter(
          (t) => t.status === "COMPLETED",
        );
        const inProgressTasks = mission.tasks.filter(
          (t) => t.status === "EXECUTING",
        );
        progress =
          mission.tasks.length > 0
            ? Math.round((completedTasks.length / mission.tasks.length) * 100)
            : 0;

        completedDimensions = completedTasks
          .map((t) => t.dimensionName)
          .filter(Boolean) as string[];
        inProgressDimensions = inProgressTasks
          .map((t) => t.dimensionName)
          .filter(Boolean) as string[];

        // 构建 TODO 列表摘要
        const pendingTasks = mission.tasks.filter(
          (t) => t.status === "PENDING" || t.status === "ASSIGNED",
        );
        todoList =
          [
            inProgressTasks.length > 0
              ? `进行中: ${inProgressTasks.map((t) => t.title).join(", ")}`
              : null,
            pendingTasks.length > 0
              ? `待处理: ${pendingTasks.map((t) => t.title).join(", ")}`
              : null,
            completedTasks.length > 0
              ? `已完成: ${completedTasks.length} 个`
              : null,
          ]
            .filter(Boolean)
            .join("\n") || "暂无任务";
      }
    }

    // 3. ★ v8.1: 构建项目配置上下文（让 Leader 了解自己的能力和团队配置）
    const projectContext = await this.buildProjectContext(topicId, missionId);

    // 4. 快速意图检测（简单情况不需要调用 AI）
    // ★ 跳过快速检测如果用户询问项目配置相关问题
    const isProjectConfigQuestion =
      sanitizedMessage.includes("工具") ||
      sanitizedMessage.includes("技能") ||
      sanitizedMessage.includes("团队") ||
      sanitizedMessage.includes("成员") ||
      sanitizedMessage.includes("知识库") ||
      sanitizedMessage.includes("配置") ||
      sanitizedMessage.includes("你能") ||
      sanitizedMessage.includes("你有");

    if (!isProjectConfigQuestion) {
      const quickResult = this.quickDecodeIntent(
        sanitizedMessage,
        progress,
        topic.name,
      );
      if (quickResult) {
        this.logger.log(
          `[decodeUserInput] Quick decode result: ${quickResult.decisionType}`,
        );
        return quickResult;
      }
    }

    // 5. 复杂情况：调用 AI 解码
    const leaderModel = await this.getReasoningModel();
    if (!leaderModel) {
      // 无推理模型时的降级处理
      return {
        decisionType: "ACKNOWLEDGE",
        understanding: "收到您的消息",
        response: `收到！我会处理您的请求："${sanitizedMessage}"`,
      };
    }

    // 6. 构建 prompt（包含项目配置上下文）
    const prompt = LEADER_DECODE_PROMPT.replace("{topic}", topic.name)
      .replace("{topicDescription}", topic.description || "无")
      .replace("{progress}", String(progress))
      .replace("{stage}", mission?.status || "未开始")
      .replace("{todoList}", todoList)
      .replace("{completedDimensions}", completedDimensions.join(", ") || "无")
      .replace(
        "{inProgressDimensions}",
        inProgressDimensions.join(", ") || "无",
      )
      .replace("{projectContext}", projectContext)
      .replace("{userMessage}", sanitizedMessage);

    // 6.5 ★ 获取对话历史（多轮上下文）
    const conversationHistory =
      await this.eventEmitter.getLeaderConversationHistory(
        topicId,
        missionId,
        5, // 最近 5 轮对话
      );

    // 7. 调用 AI（包含对话历史）
    const startTime = Date.now();

    // 构建消息数组：系统提示 + 对话历史 + 当前用户消息
    const messages: Array<{
      role: "system" | "user" | "assistant";
      content: string;
    }> = [
      {
        role: "system",
        content:
          "你是研究团队的 AI Leader。请理解用户意图并输出 JSON 格式的响应。",
      },
    ];

    // 添加对话历史（不包括当前消息，当前消息通过 prompt 发送）
    if (conversationHistory.length > 0) {
      this.logger.debug(
        `[decodeUserInput] Including ${conversationHistory.length} messages from conversation history`,
      );
      messages.push(...conversationHistory);
    }

    // 添加当前用户消息（包含完整上下文的 prompt）
    messages.push({ role: "user", content: prompt });

    const response = await this.chatFacade.chat({
      messages,
      model: leaderModel.modelId,
      skipGuardrails: true, // 对话历史含 AI 生成内容，可能触发误报
      taskProfile: {
        creativity: "low", // 解码任务需要准确性
        outputLength: "short",
      },
    });
    const latencyMs = Date.now() - startTime;

    this.logger.log(
      `[decodeUserInput] AI response in ${latencyMs}ms (with ${conversationHistory.length} history messages)`,
    );

    // 7. 解析响应
    const result = this.extractJsonFromResponse<{
      decisionType: string;
      understanding: string;
      response: string;
      todoTitle?: string;
      todoDescription?: string;
      clarifyQuestion?: string;
      clarifyOptions?: string[];
    }>(response.content, "decisionType"); // requiredKey for validation

    if (!result) {
      // 解析失败时的降级处理
      return {
        decisionType: "ACKNOWLEDGE",
        understanding: "收到您的消息",
        response: `收到！我会处理您的请求。`,
      };
    }

    // 8. 验证并返回结果
    const validTypes = [
      "DIRECT_ANSWER",
      "CREATE_TODO",
      "CLARIFY",
      "ACKNOWLEDGE",
    ];
    const decisionType = validTypes.includes(result.decisionType)
      ? (result.decisionType as
          | "DIRECT_ANSWER"
          | "CREATE_TODO"
          | "CLARIFY"
          | "ACKNOWLEDGE")
      : "ACKNOWLEDGE";

    return {
      decisionType,
      understanding: result.understanding || "收到您的消息",
      response: result.response || "收到！",
      todoTitle: result.todoTitle,
      todoDescription: result.todoDescription,
      clarifyQuestion: result.clarifyQuestion,
      clarifyOptions: result.clarifyOptions,
    };
  }

  /**
   * ★ v7.2: 为用户请求的任务选择合适的 Agent
   *
   * 功能：
   * 1. 从当前 Mission 的已有 Agent 中选择合适的
   * 2. 如果没有合适的，动态创建新 Agent
   * 3. 返回 Agent 分配信息（包含模型）
   *
   * @param topicId 专题 ID
   * @param missionId 任务 ID
   * @param taskTitle 任务标题
   * @param taskDescription 任务描述
   * @returns Agent 分配信息
   */
  async selectAgentForTask(
    _topicId: string,
    missionId: string,
    taskTitle: string,
    taskDescription?: string,
  ): Promise<AgentAssignment> {
    this.logger.log(
      `[selectAgentForTask] Selecting agent for task: "${taskTitle}"`,
    );

    // 1. 获取当前 Mission 的任务列表，了解已有 Agent
    const mission = await this.prisma.researchMission.findUnique({
      where: { id: missionId },
      include: {
        tasks: {
          where: { assignedAgentType: "dimension_researcher" },
          select: {
            assignedAgent: true,
            assignedAgentType: true,
            modelId: true,
            status: true,
          },
        },
      },
    });

    // 2. 获取可用模型列表（过滤不可用模型，优先用于对话的模型）
    const allModelsRaw = await this.chatFacade.getAvailableModelsExtended();
    const availableModels = allModelsRaw.filter((m) => m.isAvailable !== false);
    // 过滤掉推理模型（用于研究任务的应是普通对话模型）
    const chatModels = availableModels.filter((m) => !m.isReasoning);

    // 3. 统计已有 Agent 的工作负载
    const agentWorkload = new Map<string, number>();
    const agentModels = new Map<string, string>();

    if (mission?.tasks) {
      for (const task of mission.tasks) {
        const agentId = task.assignedAgent;
        const currentLoad = agentWorkload.get(agentId) || 0;
        agentWorkload.set(agentId, currentLoad + 1);
        if (task.modelId) {
          agentModels.set(agentId, task.modelId);
        }
      }
    }

    // 4. 选择策略：优先选择工作负载最少的已有 Agent
    let selectedAgentId: string;
    let selectedModelId: string;
    let agentName: string;

    // 确保有可用模型（如果没有 chat 模型，使用所有可用模型）
    const modelsToUse = chatModels.length > 0 ? chatModels : availableModels;
    const defaultModel = modelsToUse[0]?.id || "";

    if (agentWorkload.size > 0) {
      // 找出工作负载最少的 Agent
      let minLoad = Infinity;
      let minLoadAgent = "";

      for (const [agentId, load] of agentWorkload.entries()) {
        if (load < minLoad) {
          minLoad = load;
          minLoadAgent = agentId;
        }
      }

      selectedAgentId = minLoadAgent;
      selectedModelId = agentModels.get(minLoadAgent) || defaultModel;

      // 从 agentId 提取 Agent 编号用于命名
      // 格式如: researcher_1, researcher_market_trends 等
      const idMatch = selectedAgentId.match(/(\d+)$/);
      const agentNum = idMatch ? idMatch[1] : String(agentWorkload.size);
      agentName = `研究员 ${agentNum}`;

      this.logger.log(
        `[selectAgentForTask] Selected existing agent: ${selectedAgentId} (load: ${minLoad}) with model: ${selectedModelId}`,
      );
    } else {
      // 没有已有 Agent，创建新的
      const timestamp = Date.now();
      selectedAgentId = `researcher_user_${timestamp}`;

      // 随机选择模型实现多元化（确保有模型可选）
      if (modelsToUse.length > 0) {
        const modelIndex = Math.floor(Math.random() * modelsToUse.length);
        selectedModelId = modelsToUse[modelIndex].id;
      } else {
        selectedModelId = "";
      }
      agentName = "新研究员";

      this.logger.log(
        `[selectAgentForTask] Created new agent: ${selectedAgentId} with model: ${selectedModelId}`,
      );
    }

    // 5. 根据任务内容智能选择技能和工具
    const { skills, tools } = this.selectSkillsAndToolsForTask(
      taskTitle,
      taskDescription,
    );

    this.logger.log(
      `[selectAgentForTask] Selected skills: [${skills.join(", ")}], tools: [${tools.join(", ")}]`,
    );

    // 6. 记录 Leader 决策（使用 ADJUST 类型表示动态调整任务分配）
    await this.recordDecision(
      missionId,
      LeaderDecisionType.ADJUST,
      { taskTitle, taskDescription },
      {
        agentId: selectedAgentId,
        agentName,
        modelId: selectedModelId,
        skills,
        tools,
      },
      `Leader 为任务「${taskTitle}」选择了 ${agentName}（${selectedModelId}），技能：[${skills.join(", ")}]，工具：[${tools.join(", ")}]`,
    );

    return {
      agentId: selectedAgentId,
      agentName,
      agentType: "dimension_researcher",
      role: "用户请求研究员",
      modelId: selectedModelId,
      skills,
      tools,
    };
  }

  /**
   * 根据任务标题和描述智能选择技能和工具
   * 用于 Leader 对话创建的任务
   */
  private selectSkillsAndToolsForTask(
    taskTitle: string,
    taskDescription?: string,
  ): { skills: string[]; tools: string[] } {
    const content = `${taskTitle || ""} ${taskDescription || ""}`.toLowerCase();

    // 政策法规类关键词
    const policyKeywords = [
      "政策",
      "法规",
      "监管",
      "立法",
      "法案",
      "法律",
      "policy",
      "regulation",
      "regulatory",
      "legislation",
      "law",
      "compliance",
      "执法",
      "合规",
      "框架",
      "framework",
      "白宫",
      "国会",
      "联邦",
      "行政命令",
    ];

    // 市场分析类关键词
    const marketKeywords = [
      "市场",
      "竞争",
      "格局",
      "份额",
      "趋势",
      "投资",
      "融资",
      "资本",
      "商业",
      "market",
      "competition",
      "trend",
      "investment",
      "business",
      "产业",
      "行业",
      "企业",
      "公司",
    ];

    // 技术研究类关键词
    const techKeywords = [
      "技术",
      "研发",
      "创新",
      "算法",
      "架构",
      "系统",
      "technology",
      "research",
      "innovation",
      "algorithm",
      "infrastructure",
      "基础设施",
      "底层",
      "核心",
    ];

    // 数据分析类关键词
    const dataKeywords = [
      "数据",
      "统计",
      "分析",
      "指标",
      "报告",
      "data",
      "statistics",
      "metrics",
      "analysis",
      "report",
      "增长",
      "下降",
      "百分比",
    ];

    // 战略/综合类关键词
    const strategyKeywords = [
      "战略",
      "布局",
      "发展",
      "规划",
      "展望",
      "预测",
      "未来",
      "strategy",
      "development",
      "outlook",
      "forecast",
      "思想",
      "哲学",
      "根源",
      "动向",
    ];

    let skills: string[] = [];
    let tools: string[] = [];

    // 判断任务类型并选择技能和工具
    const isPolicyRelated = policyKeywords.some((kw) => content.includes(kw));
    const isMarketRelated = marketKeywords.some((kw) => content.includes(kw));
    const isTechRelated = techKeywords.some((kw) => content.includes(kw));
    const isDataRelated = dataKeywords.some((kw) => content.includes(kw));
    const isStrategyRelated = strategyKeywords.some((kw) =>
      content.includes(kw),
    );

    // 政策法规类
    if (isPolicyRelated) {
      skills.push(
        "policy-analysis",
        "regulatory-impact",
        "legislative-tracking",
      );
      tools.push("federal-register", "congress-gov", "whitehouse-news");
    }

    // 市场分析类
    if (isMarketRelated) {
      skills.push(
        "trend-analysis",
        "competitive-analysis",
        "data-interpretation",
      );
      tools.push("web-search", "data-analysis");
    }

    // 技术研究类
    if (isTechRelated) {
      skills.push("deep-dive", "comparison", "synthesis");
      tools.push("academic-search", "web-search");
    }

    // 数据分析类
    if (isDataRelated) {
      skills.push("data-interpretation", "trend-analysis");
      tools.push("data-analysis", "web-search");
    }

    // 战略/综合类
    if (isStrategyRelated) {
      skills.push(
        "future-projection",
        "cause-effect",
        "synthesis",
        "swot-analysis",
      );
      tools.push("web-search", "news");
    }

    // 评估/审核类关键词
    const evaluationKeywords = [
      "评估",
      "审查",
      "评价",
      "利弊",
      "优劣",
      "风险",
      "挑战",
      "问题",
      "evaluate",
      "assess",
      "review",
      "risk",
      "challenge",
      "opportunity",
      "swot",
      "优势",
      "劣势",
      "机遇",
      "威胁",
    ];
    const isEvaluationRelated = evaluationKeywords.some((kw) =>
      content.includes(kw),
    );
    if (isEvaluationRelated) {
      skills.push("critical-thinking", "swot-analysis");
    }

    // 去重
    skills = [...new Set(skills)];
    tools = [...new Set(tools)];

    // 如果没有匹配到任何关键词，使用默认值
    if (skills.length === 0) {
      skills = ["deep-dive", "synthesis", "data-interpretation"];
    }
    if (tools.length === 0) {
      tools = ["web-search"];
    }

    // 限制数量：skills 2-5 个，tools 1-3 个
    if (skills.length > 5) {
      skills = skills.slice(0, 5);
    }
    if (tools.length > 3) {
      tools = tools.slice(0, 3);
    }

    return { skills, tools };
  }

  /**
   * 快速意图解码（无需调用 AI）
   * 处理简单、明确的用户输入
   */
  private quickDecodeIntent(
    message: string,
    progress: number,
    topicName: string,
  ): {
    decisionType: "DIRECT_ANSWER" | "CREATE_TODO" | "CLARIFY" | "ACKNOWLEDGE";
    understanding: string;
    response: string;
  } | null {
    if (!message) return null;
    const lowerMessage = message.toLowerCase().trim();

    // 进度查询
    if (
      lowerMessage.includes("进度") ||
      lowerMessage.includes("状态") ||
      lowerMessage === "怎么样了"
    ) {
      return {
        decisionType: "DIRECT_ANSWER",
        understanding: "用户询问研究进度",
        response: `「${topicName}」研究进度：${progress}%`,
      };
    }

    // 感谢/确认
    if (
      lowerMessage === "好" ||
      lowerMessage === "好的" ||
      lowerMessage === "谢谢" ||
      lowerMessage === "收到" ||
      lowerMessage === "ok" ||
      lowerMessage === "知道了"
    ) {
      return {
        decisionType: "ACKNOWLEDGE",
        understanding: "用户表示确认",
        response: "好的，有需要随时告诉我！",
      };
    }

    // 模糊请求需要澄清
    if (
      lowerMessage === "再研究一下" ||
      lowerMessage === "改一下" ||
      lowerMessage === "不太好"
    ) {
      return {
        decisionType: "CLARIFY",
        understanding: "用户请求模糊，需要澄清",
        response: "请告诉我具体希望改进哪个方面？",
      };
    }

    // 其他情况需要 AI 处理
    return null;
  }

  /**
   * 记录 Leader 决策
   */
  private async recordDecision(
    missionId: string,
    type: LeaderDecisionType,
    input: Record<string, unknown>,
    decision: Record<string, unknown>,
    reasoning: string,
    modelUsed?: string,
    latencyMs?: number,
  ): Promise<void> {
    try {
      await this.prisma.leaderDecision.create({
        data: {
          missionId,
          type,
          input: toPrismaJson(input),
          decision: toPrismaJson(decision),
          reasoning,
          modelUsed,
          latencyMs,
        },
      });
    } catch (error) {
      this.logger.error(`[recordDecision] Failed to record decision: ${error}`);
    }
  }

  /**
   * 获取 Leader 决策历史
   */
  async getDecisionHistory(
    missionId: string,
  ): Promise<Record<string, unknown>[]> {
    return this.prisma.leaderDecision.findMany({
      where: { missionId },
      orderBy: { createdAt: "desc" },
    });
  }

  /**
   * 从 AI 响应中提取 JSON
   * 使用增强的 extractJsonFromAIResponse 工具，支持截断响应修复
   */
  private extractJsonFromResponse<T>(
    response: string,
    requiredKey?: string,
  ): T | null {
    // 处理空响应
    if (!response || response.trim().length === 0) {
      this.logger.warn("[extractJsonFromResponse] Empty response received");
      return null;
    }

    // ★ 诊断：先尝试直接 JSON.parse，记录具体错误
    try {
      JSON.parse(response);
    } catch (directError) {
      this.logger.warn(
        `[extractJsonFromResponse] Direct JSON.parse error (len=${response.length}): ${directError instanceof SyntaxError ? directError.message : "unknown"}`,
      );
    }

    const result = extractJsonFromAIResponse<T>(response, { requiredKey });

    if (result.success && result.data) {
      this.logger.debug(
        `[extractJsonFromResponse] Extracted via method: ${result.method}`,
      );
      return result.data;
    }

    this.logger.error(
      `[extractJsonFromResponse] Could not extract JSON: ${result.error || "unknown error"}`,
    );
    return null;
  }

  // ==================== 维度分析核心方法 ====================

  /**
   * Leader 规划维度分析大纲
   *
   * 核心职责：
   * 1. 理解用户意图
   * 2. 规划完整章节结构
   * 3. 确保广度和覆盖度
   */
  async planDimensionOutline(
    topic: {
      name: string;
      type: string;
      description?: string | null;
      language?: string | null;
    },
    dimension: {
      name: string;
      description?: string | null;
      searchQueries?: string[] | unknown;
    },
    evidenceSummary: string,
    figuresSummary?: string, // ★ 新增：可用图表列表
    otherDimensions?: Array<{ name: string; description?: string | null }>,
  ): Promise<DimensionOutline> {
    this.logger.log(
      `[planDimensionOutline] Planning outline for dimension: ${dimension.name}`,
    );

    const focusAreas = Array.isArray(dimension.searchQueries)
      ? (dimension.searchQueries as string[]).join(", ")
      : "无";

    const otherDimensionsInfo =
      otherDimensions && otherDimensions.length > 0
        ? otherDimensions
            .filter((d) => d.name !== dimension.name)
            .map(
              (d) =>
                `- **${d.name}**${d.description ? `：${d.description}` : ""}`,
            )
            .join("\n")
        : "无其他维度";

    const prompt = DIMENSION_OUTLINE_PROMPT.replace("{topicName}", topic.name)
      .replace("{topicType}", topic.type)
      .replace("{topicDescription}", topic.description || "无")
      .replace(/\{dimensionName\}/g, () => dimension.name)
      .replace("{dimensionDescription}", dimension.description || "无")
      .replace("{focusAreas}", focusAreas)
      .replace("{evidenceSummary}", evidenceSummary)
      .replace("{otherDimensionsInfo}", otherDimensionsInfo)
      .replace(
        "{languageInstruction}",
        getLanguageInstruction(topic.language || "zh"),
      );

    // ★ 注入图表分配信息
    const figuresSection = figuresSummary
      ? `\n\n## 可用图表资源\n${figuresSummary}\n\n**图表分配指令**：\n1. 为每个 section 分配 0-2 个**内容直接相关**的图表\n2. 每张图只能分配给一个 section\n3. 在 sections 的每个条目中新增 "allocatedFigures" 字段\n\n**相关性判断标准（严格遵守）**：\n- 图表的标题/描述中的**核心主题词**必须与 section 的标题或 keyPoints 直接相关\n- 例如："硬件演进"图表 → 只能分配给讨论硬件/算力的 section，不能分配给讨论注意力机制的 section\n- 例如："机器人基础模型"图表 → 只能分配给讨论机器人/具身智能的 section，不能分配给讨论 GPT 的 section\n- 如果没有直接相关的图表，该 section 的 allocatedFigures 留空数组 []\n- **宁缺勿滥**：不确定是否相关时，不分配\n\n**relevanceReason 必须具体说明**：图表中的哪个关键词/主题与 section 的哪个要点直接对应`
      : "";
    const finalPrompt = prompt + figuresSection;

    // ★ 诊断日志：记录实际 prompt 大小和各模板变量大小
    const OVERSIZED_PROMPT_CHARS = 50_000;
    const PROMPT_PREVIEW_LEN = 200;
    this.logger.log(
      `[planDimensionOutline] Prompt size: finalPrompt=${finalPrompt.length} chars, ` +
        `evidenceSummary=${evidenceSummary.length}, figuresSection=${figuresSection.length}`,
    );

    if (finalPrompt.length > OVERSIZED_PROMPT_CHARS) {
      this.logger.error(
        `[planDimensionOutline] ⚠ OVERSIZED finalPrompt (${finalPrompt.length} chars)! ` +
          `First ${PROMPT_PREVIEW_LEN}: ${finalPrompt.substring(0, PROMPT_PREVIEW_LEN)}... | ` +
          `Last ${PROMPT_PREVIEW_LEN}: ...${finalPrompt.substring(finalPrompt.length - PROMPT_PREVIEW_LEN)}`,
      );
    }

    // ★ 添加重试机制，处理 API 临时故障
    const MAX_RETRIES = 3;
    const RETRY_DELAY_MS = 2000;
    let lastError: Error | null = null;
    const failedModelIds = new Set<string>();

    for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {
      let currentModelId = "";
      try {
        // ★ 最后一次尝试时回退到非推理模型，增加容错性
        const useReasoning = attempt < MAX_RETRIES;
        let leaderModel = useReasoning
          ? await this.getReasoningModel()
          : await this.chatFacade.selectModel({ requireReasoning: false });

        // ★ 如果选出的模型之前因配额/欠费失败，尝试选择其他模型
        const selectedId =
          leaderModel &&
          ("modelId" in leaderModel ? leaderModel.modelId : leaderModel.id);
        if (selectedId && failedModelIds.has(selectedId)) {
          this.logger.warn(
            `[planDimensionOutline] Model ${selectedId} previously failed (quota/billing), selecting alternative`,
          );
          const allModels = await this.chatFacade.getAvailableModelsExtended();
          const alternativeModel = allModels.find(
            (m) => m.isAvailable !== false && !failedModelIds.has(m.id),
          );
          if (alternativeModel) {
            leaderModel = alternativeModel;
          }
        }

        if (!leaderModel) {
          throw new ServiceUnavailableException(
            "No model available for Leader",
          );
        }
        const modelId =
          "modelId" in leaderModel ? leaderModel.modelId : leaderModel.id;
        currentModelId = modelId;
        this.logger.log(
          `[planDimensionOutline] Attempt ${attempt}/${MAX_RETRIES}: Using model ${modelId}${!useReasoning ? " (non-reasoning fallback)" : ""}`,
        );

        const startTime = Date.now();
        const response = await this.chatFacade.chat({
          messages: [
            {
              role: "system",
              content:
                '你是研究协调专家 Leader，负责规划维度分析大纲。你必须只输出合法的 JSON 对象，不要输出任何解释文字、markdown 代码块标记或其他非 JSON 内容。JSON 必须包含 "sections" 数组。',
            },
            { role: "user", content: finalPrompt },
          ],
          model: modelId,
          skipGuardrails: true, // 内部系统调用，研究证据含外部搜索数据会触发误报
          responseFormat: "json",
          taskProfile: {
            creativity: "medium",
            outputLength: "long",
          },
        });
        const latencyMs = Date.now() - startTime;

        // ★ 预处理：剥离推理模型的思考标签（如 <think>...</think>）
        let rawContent = response.content;
        rawContent = rawContent
          .replace(/<think>[\s\S]*?<\/think>/gi, "")
          .trim();
        rawContent = rawContent
          .replace(/<reasoning>[\s\S]*?<\/reasoning>/gi, "")
          .trim();

        // ★ 关键修复：检查 API 是否返回了错误
        if (response.isError) {
          const errorContent = rawContent.slice(0, 200);
          const lc = errorContent.toLowerCase();
          this.logger.warn(
            `[planDimensionOutline] Attempt ${attempt}/${MAX_RETRIES}: API returned error: ${errorContent}`,
          );

          // ★ 积分不足：不重试，直接抛出让 mission 快速失败
          if (
            lc.includes("insufficient credits") ||
            lc.includes("insufficient_credits")
          ) {
            throw new Error(`[INSUFFICIENT_CREDITS] ${errorContent}`);
          }

          // ★ 上下文过长：不重试（同样的 prompt 换模型也不会变小），直接失败
          if (
            lc.includes("context_too_long") ||
            lc.includes("context length") ||
            lc.includes("too many tokens") ||
            lc.includes("reduce the length of the messages")
          ) {
            throw new Error(
              `[CONTEXT_TOO_LONG] Prompt too large for any model. ${errorContent}`,
            );
          }

          // ★ 检测配额超限错误，这类错误切换模型后可能成功
          const isQuotaError =
            lc.includes("429") ||
            lc.includes("402") ||
            lc.includes("quota") ||
            lc.includes("rate limit") ||
            lc.includes("payment") ||
            lc.includes("billing") ||
            lc.includes("temporarily unavailable");
          if (isQuotaError) {
            failedModelIds.add(modelId);
          }
          lastError = new Error(`API error: ${rawContent.slice(0, 100)}`);
          if (attempt < MAX_RETRIES) {
            // 配额错误不需要等太久，快速切换到下一个模型
            await this.delay(isQuotaError ? 500 : RETRY_DELAY_MS * attempt);
            continue;
          }
          // ★ 通用兜底：最后一次重试仍为 API 错误，跳出循环避免错误内容被当 JSON 解析
          break;
        }

        // ★ 检测是否返回了 HTML 错误页面（API 故障特征）
        if (rawContent.includes("<!DOCTYPE") || rawContent.includes("<html")) {
          this.logger.warn(
            `[planDimensionOutline] Attempt ${attempt}/${MAX_RETRIES}: API returned HTML error page, retrying...`,
          );
          lastError = new Error("API returned HTML error page instead of JSON");
          if (attempt < MAX_RETRIES) {
            await this.delay(RETRY_DELAY_MS * attempt);
            continue;
          }
          // ★ 最后一次重试仍为 HTML，跳出循环避免 HTML 被当 JSON 解析
          break;
        }

        const outline = this.extractJsonFromResponse<DimensionOutline>(
          rawContent,
          "sections", // requiredKey for validation
        );

        if (!outline?.sections || outline.sections.length === 0) {
          // ★ 记录原始输出前500字符，帮助诊断 JSON 解析失败原因
          this.logger.warn(
            `[planDimensionOutline] Attempt ${attempt}/${MAX_RETRIES}: Failed to parse JSON. Raw output (first 500 chars): ${rawContent.slice(0, 500)}`,
          );
          lastError = new Error("Failed to parse dimension outline JSON");
          if (attempt < MAX_RETRIES) {
            await this.delay(RETRY_DELAY_MS * attempt);
            continue;
          }
        } else {
          // ★ 成功
          // ★ 诊断日志：记录每个 section 的 allocatedFigures 分配情况
          const figSummary = outline.sections
            .map((s) => `${s.title}:${s.allocatedFigures?.length ?? 0}figs`)
            .join(", ");
          this.logger.log(
            `[planDimensionOutline] Created outline with ${outline.sections.length} sections in ${latencyMs}ms (attempt ${attempt}). Figures: [${figSummary}]`,
          );
          return outline;
        }
      } catch (error) {
        const errorMsg =
          error instanceof Error ? error.message : "Unknown error";
        this.logger.warn(
          `[planDimensionOutline] Attempt ${attempt}/${MAX_RETRIES} failed: ${errorMsg}`,
        );
        // ★ 异常级别也检测计费错误，标记模型避免重选
        const errLc = errorMsg.toLowerCase();
        if (
          errLc.includes("402") ||
          errLc.includes("quota") ||
          errLc.includes("payment") ||
          errLc.includes("insufficient") ||
          errLc.includes("billing")
        ) {
          failedModelIds.add(currentModelId);
        }
        lastError =
          error instanceof Error ? error : new Error("Unknown API error");

        // ★ 积分不足：不重试，直接向上抛出
        if (errorMsg.includes("INSUFFICIENT_CREDITS")) {
          throw lastError;
        }

        if (attempt < MAX_RETRIES) {
          await this.delay(
            failedModelIds.has(currentModelId) ? 500 : RETRY_DELAY_MS * attempt,
          );
        }
      }
    }

    // ★ 所有重试都失败
    this.logger.error(
      `[planDimensionOutline] All ${MAX_RETRIES} attempts failed for dimension: ${dimension.name}`,
    );
    throw new InternalServerErrorException(
      `Failed to parse dimension outline after ${MAX_RETRIES} attempts: ${lastError?.message || "Unknown error"}`,
    );
  }

  /**
   * 根据维度内容智能选择默认技能
   * 当 AI 未返回 skills 时，基于维度名称和描述选择合适的技能
   */
  private selectDefaultSkillsForDimension(
    assignment: { assignedDimensions?: string[] },
    dimensions: Array<{ id: string; name: string; description?: string }>,
  ): string[] {
    // 基础技能（始终包含，data_interpretation 作为通用分析技能始终保留）
    const skills = new Set(["deep-dive", "synthesis", "data-interpretation"]);

    // 收集该 Agent 负责的维度名称和描述
    const dimTexts = (assignment.assignedDimensions || [])
      .map((dimId) => {
        const dim = dimensions.find((d) => d.id === dimId);
        return dim ? `${dim.name} ${dim.description || ""}` : "";
      })
      .join(" ")
      .toLowerCase();

    // 关键词 → 技能映射
    const keywordSkillMap: Array<{
      keywords: string[];
      skill: string;
    }> = [
      {
        keywords: ["趋势", "走势", "变化", "增长", "下降", "trend", "growth"],
        skill: "trend-analysis",
      },
      {
        keywords: [
          "竞争",
          "竞品",
          "对手",
          "格局",
          "market share",
          "competitor",
          "competition",
        ],
        skill: "competitive-analysis",
      },
      {
        keywords: [
          "对比",
          "比较",
          "差异",
          "versus",
          "vs",
          "compare",
          "comparison",
        ],
        skill: "comparison",
      },
      {
        keywords: [
          "数据",
          "指标",
          "统计",
          "data",
          "metric",
          "statistics",
          "分析",
        ],
        skill: "data-interpretation",
      },
      {
        keywords: ["未来", "预测", "展望", "forecast", "outlook", "projection"],
        skill: "future-projection",
      },
      {
        keywords: [
          "原因",
          "影响",
          "因果",
          "驱动",
          "cause",
          "effect",
          "impact",
          "driver",
        ],
        skill: "cause-effect",
      },
      {
        keywords: [
          "评估",
          "优劣",
          "利弊",
          "风险",
          "swot",
          "strength",
          "weakness",
          "优势",
          "劣势",
          "机遇",
          "威胁",
        ],
        skill: "swot-analysis",
      },
      {
        keywords: [
          "审视",
          "批判",
          "反思",
          "质疑",
          "critical",
          "evaluate",
          "问题",
          "挑战",
        ],
        skill: "critical-thinking",
      },
    ];

    for (const { keywords, skill } of keywordSkillMap) {
      if (keywords.some((kw) => dimTexts.includes(kw))) {
        skills.add(skill);
      }
    }

    // 限制最多 5 个技能（避免 prompt 膨胀）
    const result = [...skills];
    return result.length > 5 ? result.slice(0, 5) : result;
  }

  /** 延迟函数 */
  private delay(ms: number): Promise<void> {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }

  /**
   * Leader 规划全局协调大纲（Phase 2）
   *
   * 核心职责：
   * 1. 全局视角 - 同时查看所有维度的搜索结果
   * 2. 协调去重 - 确保各维度之间分工明确，避免重复
   * 3. 规划大纲 - 为每个维度规划完整章节结构
   *
   * @param topic 研究专题
   * @param dimensionSearchResults 所有维度的搜索结果摘要
   * @returns 全局协调的大纲
   */
  async planGlobalOutline(
    topic: {
      name: string;
      type: string;
      description?: string | null;
      language?: string | null;
    },
    dimensionSearchResults: Array<{
      dimensionId: string;
      dimensionName: string;
      dimensionDescription?: string | null;
      evidenceSummary: string;
      figuresSummary: string;
      searchQueries?: string[] | unknown;
    }>,
  ): Promise<GlobalOutline> {
    this.logger.log(
      `[planGlobalOutline] Planning global coordinated outline for ${dimensionSearchResults.length} dimensions`,
    );

    // 构建所有维度的搜索结果摘要（限制每个维度摘要长度，避免 token 溢出）
    const MAX_EVIDENCE_CHARS = 1200;
    const MAX_FIGURES_CHARS = 300;
    const dimensionSearchResultsText = dimensionSearchResults
      .map((d, index) => {
        const queries = Array.isArray(d.searchQueries)
          ? (d.searchQueries as string[]).join(", ")
          : "无";
        const evidenceText = (d.evidenceSummary || "").substring(
          0,
          MAX_EVIDENCE_CHARS,
        );
        const figuresText = (d.figuresSummary || "").substring(
          0,
          MAX_FIGURES_CHARS,
        );
        return `### 维度 ${index + 1}: ${d.dimensionName}

**描述**: ${d.dimensionDescription || "无"}
**搜索重点**: ${queries}

**搜索结果摘要**:
${evidenceText}

${figuresText ? `**可用图表**:\n${figuresText}` : ""}

---`;
      })
      .join("\n\n");

    const prompt = GLOBAL_OUTLINE_PROMPT.replace("{topicName}", topic.name)
      .replace("{topicType}", topic.type)
      .replace("{topicDescription}", topic.description || "无")
      .replace("{dimensionSearchResults}", dimensionSearchResultsText)
      .replace(
        "{languageInstruction}",
        getLanguageInstruction(topic.language || "zh"),
      );

    // 重试机制
    const MAX_RETRIES = 3;
    const RETRY_DELAY_MS = 2000;
    let lastError: Error | null = null;
    const failedModelIdsGlobal = new Set<string>();

    for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {
      let currentModelId = "";
      try {
        let leaderModel = await this.getReasoningModel();

        // ★ 如果选出的模型之前因配额/欠费失败，尝试选择其他模型
        if (leaderModel && failedModelIdsGlobal.has(leaderModel.modelId)) {
          this.logger.warn(
            `[planGlobalOutline] Model ${leaderModel.modelId} previously failed (quota/billing), selecting alternative`,
          );
          const allModels = await this.chatFacade.getAvailableModelsExtended();
          const alternativeModel = allModels.find(
            (m) => m.isAvailable !== false && !failedModelIdsGlobal.has(m.id),
          );
          if (alternativeModel) {
            leaderModel = {
              modelId: alternativeModel.id,
              modelName: alternativeModel.name,
              provider: alternativeModel.provider,
              isReasoning: alternativeModel.isReasoning ?? false,
            };
          }
        }

        if (!leaderModel) {
          throw new ServiceUnavailableException(
            "No reasoning model available for Leader",
          );
        }
        currentModelId = leaderModel.modelId;
        this.logger.log(
          `[planGlobalOutline] Attempt ${attempt}/${MAX_RETRIES}: Using model ${leaderModel.modelId}`,
        );

        const startTime = Date.now();
        const response = await this.chatFacade.chat({
          messages: [
            {
              role: "system",
              content:
                "你是研究协调专家 Leader，负责全局协调各维度的研究大纲。请输出 JSON 格式。",
            },
            { role: "user", content: prompt },
          ],
          model: leaderModel.modelId,
          skipGuardrails: true, // 内部系统调用，汇聚所有维度数据
          responseFormat: "json",
          taskProfile: {
            creativity: "medium",
            outputLength: "extended",
          },
        });
        const latencyMs = Date.now() - startTime;

        // ★ 预处理：剥离推理模型的思考标签（如 <think>...</think>）
        let rawContent = response.content;
        rawContent = rawContent
          .replace(/<think>[\s\S]*?<\/think>/gi, "")
          .trim();
        rawContent = rawContent
          .replace(/<reasoning>[\s\S]*?<\/reasoning>/gi, "")
          .trim();

        if (response.isError) {
          const errorContent = rawContent.slice(0, 200);
          const lc = errorContent.toLowerCase();
          this.logger.warn(
            `[planGlobalOutline] Attempt ${attempt}/${MAX_RETRIES}: API returned error: ${errorContent}`,
          );

          // ★ 积分不足：不重试，直接抛出让 mission 快速失败
          if (
            lc.includes("insufficient credits") ||
            lc.includes("insufficient_credits")
          ) {
            throw new Error(
              `[INSUFFICIENT_CREDITS] ${rawContent.slice(0, 200)}`,
            );
          }

          // ★ 上下文过长：不重试（同样的 prompt 换模型也不会变小），直接失败
          if (
            lc.includes("context_too_long") ||
            lc.includes("context length") ||
            lc.includes("too many tokens") ||
            lc.includes("reduce the length of the messages")
          ) {
            throw new Error(
              `[CONTEXT_TOO_LONG] Prompt too large for any model. ${errorContent}`,
            );
          }

          const isQuotaError =
            lc.includes("429") ||
            lc.includes("402") ||
            lc.includes("quota") ||
            lc.includes("rate limit") ||
            lc.includes("payment") ||
            lc.includes("billing") ||
            lc.includes("temporarily unavailable");
          if (isQuotaError) {
            failedModelIdsGlobal.add(leaderModel.modelId);
          }
          lastError = new Error(`API error: ${rawContent.slice(0, 100)}`);
          if (attempt < MAX_RETRIES) {
            await this.delay(isQuotaError ? 500 : RETRY_DELAY_MS * attempt);
            continue;
          }
          // ★ 通用兜底：最后一次重试仍为 API 错误，跳出循环避免错误内容被当 JSON 解析
          break;
        }

        if (rawContent.includes("<!DOCTYPE") || rawContent.includes("<html")) {
          this.logger.warn(
            `[planGlobalOutline] Attempt ${attempt}/${MAX_RETRIES}: API returned HTML error page, retrying...`,
          );
          lastError = new Error("API returned HTML error page instead of JSON");
          if (attempt < MAX_RETRIES) {
            await this.delay(RETRY_DELAY_MS * attempt);
            continue;
          }
          // ★ 最后一次重试仍为 HTML，跳出循环避免 HTML 被当 JSON 解析
          break;
        }

        const globalOutline = this.extractJsonFromResponse<GlobalOutline>(
          rawContent,
          "dimensions",
        );

        if (
          !globalOutline?.dimensions ||
          globalOutline.dimensions.length === 0
        ) {
          this.logger.warn(
            `[planGlobalOutline] Attempt ${attempt}/${MAX_RETRIES}: Failed to parse JSON, retrying...`,
          );
          lastError = new Error("Failed to parse global outline JSON");
          if (attempt < MAX_RETRIES) {
            await this.delay(RETRY_DELAY_MS * attempt);
            continue;
          }
        } else {
          // Validate: ensure all input dimensions have corresponding outline entries
          const inputNames = new Set(
            dimensionSearchResults.map((d) => d.dimensionName),
          );
          const outlineNames = new Set(
            globalOutline.dimensions.map((d) => d.dimensionName),
          );
          const missing = [...inputNames].filter((n) => !outlineNames.has(n));
          if (missing.length > 0) {
            this.logger.warn(
              `[planGlobalOutline] Outline missing ${missing.length} dimensions: ${missing.join(", ")}. Adding stubs.`,
            );
            // Add stub outlines for missing dimensions
            const APPENDIX_KEYWORDS =
              /附录|方法论|参考文献|指标体系|术语|工具清单|glossary|appendix|methodology/i;
            for (const name of missing) {
              const inputDim = dimensionSearchResults.find(
                (d) => d.dimensionName === name,
              );
              // ★ B4: 附录类维度字数减半
              const isAppendixLike = APPENDIX_KEYWORDS.test(name);
              const stubWords = isAppendixLike ? 400 : 800;
              globalOutline.dimensions.push({
                dimensionId: inputDim?.dimensionId || "",
                dimensionName: name,
                crossDimensionNotes: "",
                outline: {
                  intentUnderstanding: {
                    coreQuestion: name,
                    scope: { included: [name], excluded: [] },
                    expectedDepth: isAppendixLike ? "overview" : "detailed",
                    targetAudience: "general",
                    keyFocusAreas: [name],
                  },
                  sections: [
                    {
                      id: `stub-${name}`,
                      title: name,
                      description: "综合分析",
                      keyPoints: ["综合分析"],
                      targetWords: stubWords,
                      evidenceRequirements: { minReferences: 2 },
                    },
                  ],
                  executionPlan: {
                    parallelGroups: [[`stub-${name}`]],
                    estimatedTotalWords: stubWords,
                  },
                },
              });
            }
          }

          this.logger.log(
            `[planGlobalOutline] Created global outline for ${globalOutline.dimensions.length} dimensions in ${latencyMs}ms (attempt ${attempt})`,
          );
          return globalOutline;
        }
      } catch (error) {
        const errMsg = error instanceof Error ? error.message : "Unknown error";
        this.logger.warn(
          `[planGlobalOutline] Attempt ${attempt}/${MAX_RETRIES} failed: ${errMsg}`,
        );
        // ★ 异常级别也检测计费错误，标记模型避免重选
        const errLc = errMsg.toLowerCase();
        if (
          errLc.includes("402") ||
          errLc.includes("quota") ||
          errLc.includes("payment") ||
          errLc.includes("insufficient") ||
          errLc.includes("billing")
        ) {
          failedModelIdsGlobal.add(currentModelId);
        }
        lastError =
          error instanceof Error ? error : new Error("Unknown API error");
        if (attempt < MAX_RETRIES) {
          await this.delay(
            failedModelIdsGlobal.has(currentModelId)
              ? 500
              : RETRY_DELAY_MS * attempt,
          );
        }
      }
    }

    this.logger.error(`[planGlobalOutline] All ${MAX_RETRIES} attempts failed`);
    throw new InternalServerErrorException(
      `Failed to parse global outline after ${MAX_RETRIES} attempts: ${lastError?.message || "Unknown error"}`,
    );
  }

  /**
   * Leader 整合各章节内容
   *
   * 将多个章节整合成完整报告：
   * - 添加过渡语句
   * - 提取关键发现
   * - 生成总结
   */
  async integrateDimensionResults(
    dimension: { name: string; description?: string | null },
    sectionResults: Array<{ title: string; content: string }>,
    topicLanguage?: string | null,
  ): Promise<IntegratedDimensionResult> {
    this.logger.log(
      `[integrateDimensionResults] Integrating ${sectionResults.length} sections for ${dimension.name}`,
    );

    // 如果只有一个章节，直接返回（但仍提取关键发现）
    if (sectionResults.length === 1) {
      const content = sectionResults[0].content;
      const keyFindings = this.extractKeyFindingsFromContent(content);
      return {
        content,
        metadata: {
          summary: content.substring(0, 200),
          keyFindings,
          confidenceLevel: "medium",
        },
        evidenceUsed: this.extractEvidenceIds(content),
        totalWords: content.length,
      };
    }

    const leaderModel = await this.getReasoningModel();

    // 构建章节内容（不添加编号和分割线——编号由 numberSubHeadings 统一处理）
    const sectionsContent = sectionResults
      .map((s) => `### ${s.title}\n\n${s.content}`)
      .join("\n\n");

    // 如果没有推理模型，使用简单拼接（但仍提取关键发现）
    if (!leaderModel) {
      const keyFindings = this.extractKeyFindingsFromContent(sectionsContent);
      return {
        content: sectionsContent,
        metadata: {
          summary: `关于"${dimension.name}"的分析报告。`,
          keyFindings,
          confidenceLevel: "medium",
        },
        evidenceUsed: this.extractEvidenceIds(sectionsContent),
        totalWords: sectionsContent.length,
      };
    }

    // ★ 保留完整章节内容（不压缩），仅用AI提取摘要和关键发现
    const fullContent = sectionsContent;
    const totalWords = fullContent.length;

    // 用AI提取摘要和关键发现（但不重写正文）
    let summary = `关于"${dimension.name}"的深度分析报告。`;
    let keyFindings = this.extractKeyFindingsFromContent(fullContent);

    try {
      const isEnglish = topicLanguage === "en";
      const metaPrompt = isEnglish
        ? `Read the following research content and output a JSON summary with key findings:

Dimension: ${dimension.name}
${dimension.description || ""}

Content (first 8000 chars):
${fullContent.substring(0, 8000)}

Output format:
\`\`\`json
{
  "summary": "200-300 word dimension summary",
  "keyFindings": ["Key finding 1 (50-100 words)", "Key finding 2", ...]
}
\`\`\`
Requirements: summary 200-300 words, keyFindings 5-8 items, each 50-100 words.`
        : `请阅读以下研究内容，输出JSON格式的摘要和关键发现：

维度：${dimension.name}
${dimension.description || ""}

内容（前8000字）：
${fullContent.substring(0, 8000)}

输出格式：
\`\`\`json
{
  "summary": "200-300字的维度总结摘要",
  "keyFindings": ["关键发现1（50-100字）", "关键发现2", ...]
}
\`\`\`
要求：summary 200-300字，keyFindings 5-8条，每条50-100字。`;

      const metaResponse = await this.chatFacade.chat({
        messages: [
          {
            role: "system",
            content: isEnglish
              ? "You are a research report integration expert. Output JSON."
              : "你是研究报告整合专家，请输出JSON。",
          },
          { role: "user", content: metaPrompt },
        ],
        model: leaderModel.modelId,
        skipGuardrails: true, // 内部系统调用，维度报告内容
        responseFormat: "json",
        taskProfile: { creativity: "low", outputLength: "medium" },
      });

      const metaResult = this.extractJsonFromResponse<{
        summary?: string;
        keyFindings?: string[];
      }>(metaResponse.content, "summary");

      if (metaResult?.summary) summary = metaResult.summary;
      if (metaResult?.keyFindings?.length) keyFindings = metaResult.keyFindings;
    } catch (err) {
      this.logger.warn(
        `[integrateDimensionResults] Meta extraction failed, using fallback: ${(err as Error).message}`,
      );
    }

    this.logger.log(
      `[integrateDimensionResults] Preserved ${sectionResults.length} sections (${totalWords} chars), ${keyFindings.length} keyFindings`,
    );

    return {
      content: fullContent,
      metadata: {
        summary,
        keyFindings,
        confidenceLevel: "medium",
      },
      evidenceUsed: this.extractEvidenceIds(fullContent),
      totalWords,
    };
  }

  /**
   * 从内容中提取证据 ID
   */
  private extractEvidenceIds(content: string): string[] {
    const matches = content.match(/\[temp-\d+-\d+\]/g) || [];
    return [...new Set(matches.map((m) => m.slice(1, -1)))];
  }

  /**
   * 从内容中自动提取关键发现
   * 用于 fallback 场景（单章节、无推理模型、整合失败等）
   * 策略：
   * 1. 查找带有特定标记的句子（如"关键"、"重要"、"核心"等）
   * 2. 查找 Markdown 标题后的第一句话
   * 3. 提取带引用的观点
   */
  private extractKeyFindingsFromContent(content: string): string[] {
    const findings: string[] = [];

    // 1. 查找明确标注的关键发现（如"关键发现："后面的内容）
    const markedFindingsMatch = content.match(
      /(?:关键发现|核心观点|主要结论|重要发现)[：:]\s*([^\n]+)/g,
    );
    if (markedFindingsMatch) {
      for (const match of markedFindingsMatch) {
        const finding = match
          .replace(/(?:关键发现|核心观点|主要结论|重要发现)[：:]\s*/, "")
          .trim();
        if (finding.length > 10 && finding.length < 200) {
          findings.push(finding);
        }
      }
    }

    // 2. 从列表项中提取（Markdown 列表）
    const listItemMatches = content.match(/^[-*]\s+.{20,150}(?:。|$)/gm);
    if (listItemMatches && findings.length < 5) {
      for (const item of listItemMatches.slice(0, 5 - findings.length)) {
        const finding = item.replace(/^[-*]\s+/, "").trim();
        if (!findings.includes(finding)) {
          findings.push(finding);
        }
      }
    }

    // 3. 从标题下方第一句话提取（Markdown 标题）
    const headerMatches = content.match(
      /^#{2,4}\s+[^\n]+\n+([^#\n][^\n]{20,150})/gm,
    );
    if (headerMatches && findings.length < 5) {
      for (const match of headerMatches.slice(0, 3)) {
        const lines = match.split("\n").filter((l) => l.trim());
        if (lines.length > 1) {
          const sentence = lines[1].trim().replace(/^[-*]\s+/, "");
          if (sentence.length > 20 && !findings.includes(sentence)) {
            findings.push(sentence);
          }
        }
      }
    }

    // 去重并限制数量
    return [...new Set(findings)].slice(0, 5);
  }
}
