/**
 * AG-11-SY · Synthesizer spec
 * Produces final mission report from dimension metas + cross-dim analysis.
 */

import type { IAgentSpec } from "@/modules/ai-engine/harness/abstractions";
import {
  SynthesisResultSchema,
  type DimensionMeta,
  type QualityReview,
  type SynthesisResult,
} from "../harness/agents/schemas";

export interface SynthesizerInput {
  readonly missionId: string;
  readonly topicId: string;
  readonly topicName: string;
  readonly dimensionMetas: ReadonlyArray<DimensionMeta>;
  readonly integratedSectionsPerDim: Record<string, string>;
  readonly overallReview?: QualityReview;
  readonly userPrompt?: string;
  readonly language: string;
}

export const SYNTHESIZER_SPEC: IAgentSpec<SynthesizerInput, SynthesisResult> = {
  identity: {
    role: {
      id: "AG-11-SY",
      name: "Report Synthesizer",
      description: "从 dimension metas 合成最终 mission 报告。",
      workStyle: "structured",
    },
    persona: { tone: "formal", language: "zh-CN", style: "首席研究编辑" },
    goal: {
      summary:
        "产出 SynthesisResult（executiveSummary + fullMarkdown + highlights + riskMatrix）",
    },
    constraints: {
      maxIterations: 4,
      maxTokens: 80_000,
      maxWallTimeMs: 240_000,
      safetyLevel: "standard",
    },
    tools: ["rag-search", "TL-04-DIMMEM"],
    forbiddenTools: ["TL-02-EVSAVE"],
  },
  taskProfile: { creativity: "medium", outputLength: "extended" },
  outputSchema: SynthesisResultSchema,

  buildSystemPrompt: () =>
    [
      "你是报告综合专家。基于 dimension metas + 整合后的章节产出最终报告。",
      "约束（严厉）：",
      "1. executiveSummary 300-2000 字，含 3-5 核心结论 + 3-5 量化指标 + 2-3 风险 + 2-3 行动建议",
      "2. crossDimensionAnalysis 识别 2-3 因果链（≥50 字）",
      "3. riskMatrix 分 high/medium/low 三档，每条有 relatedDimensions",
      "4. recommendations 按 P0/P1/P2 排序，每条关联具体维度",
      "5. **严禁**重写 dimension 正文；**严禁**新增来源；**严禁**臆造数据",
      "6. highlights ≥ 3 条 KEY_FINDING",
      "",
      "严格 JSON 输出。",
    ].join("\n"),

  buildUserPrompt: (ctx) => {
    const { input } = ctx;
    return [
      `missionId: ${input.missionId}`,
      `topic: ${input.topicName}（id=${input.topicId}）`,
      `language: ${input.language}`,
      input.userPrompt ? `userPrompt: ${input.userPrompt}` : "",
      "",
      "dimensionMetas:",
      ...input.dimensionMetas.map(
        (m) =>
          `  - ${m.dimensionName}\n    summary: ${m.summary}\n    keyFindings: ${m.keyFindings.join(" | ")}\n    evidenceCount: ${m.evidenceCount}`,
      ),
      "",
      input.overallReview
        ? `overallReview score: ${input.overallReview.overallScore}`
        : "",
      "",
      "请输出 SynthesisResult JSON。",
    ]
      .filter(Boolean)
      .join("\n");
  },

  stubFn: async (ctx) => {
    const { input } = ctx;
    const execSummary =
      `# 执行摘要\n\n本报告就 ${input.topicName} 从 ${input.dimensionMetas.length} 个维度展开系统研究。` +
      input.dimensionMetas
        .map((m) => `\n\n**${m.dimensionName}**：${m.summary.slice(0, 200)}...`)
        .join("") +
      "\n\n综合分析表明：上述研究具有结构性机会与阶段性风险并存的特征。（stub synthesis）";

    const fullMarkdown =
      `# ${input.topicName} · 综合研究报告\n\n` +
      execSummary +
      "\n\n" +
      input.dimensionMetas
        .map(
          (m, idx) =>
            `## ${idx + 1}. ${m.dimensionName}\n\n${m.summary}\n\n` +
            m.keyFindings
              .slice(0, 3)
              .map((kf, i) => `- 发现 ${i + 1}：${kf}`)
              .join("\n"),
        )
        .join("\n\n") +
      "\n\n## 结论\n\n" +
      `综合以上 ${input.dimensionMetas.length} 个维度分析，${input.topicName} 的演进呈现复合型趋势（stub）。` +
      "（stub：核心观察包括各维度间存在系统性关联、风险与机会并存。）" +
      `\n\n> Generated by harness mission ${input.missionId}`;

    const highlights = input.dimensionMetas.slice(0, 5).map((m, idx) => ({
      type: "KEY_FINDING" as const,
      text: `${m.dimensionName}：核心发现 ${idx + 1}（${m.keyFindings[0] ?? ""}）`,
    }));

    return {
      missionId: input.missionId,
      executiveSummary: execSummary.slice(0, 3500),
      preface: `本报告针对 ${input.topicName} 进行深度研究（stub preface ≥50 字）。使用 ${input.dimensionMetas.length} 个分析维度，综合得出结论与建议。`,
      fullMarkdown,
      highlights:
        highlights.length >= 3
          ? highlights
          : [
              ...highlights,
              ...Array.from({ length: 3 - highlights.length }).map((_, i) => ({
                type: "KEY_FINDING" as const,
                text: `补齐 stub highlight ${i + 1}（stub）`,
              })),
            ],
      crossDimensionAnalysis:
        `跨维度分析：${input.dimensionMetas.map((m) => m.dimensionName).join("、")} 之间形成互补与制约关系，` +
        "其中趋势层面的共振、挑战层面的叠加、机会层面的互补三条主线清晰可见（stub cross-dimension analysis）。",
      riskMatrix: [
        {
          level: "medium" as const,
          description: "stub: 数据时效性风险",
          relatedDimensions: input.dimensionMetas
            .slice(0, 2)
            .map((m) => m.dimensionId),
        },
      ],
      recommendations: [
        {
          priority: "P1" as const,
          action: `针对 ${input.topicName} 补充更多时效数据`,
          rationale: "避免数据过期带来的结论偏差",
          relatedDimensions:
            input.dimensionMetas.length > 0
              ? [input.dimensionMetas[0].dimensionId]
              : ["stub-dim-1"],
        },
      ],
    };
  },
};
