/**
 * AG-11-SY · Synthesizer spec
 * Produces final mission report from dimension metas + cross-dim analysis.
 */

import type { IAgentSpec } from "@/modules/ai-engine/harness/abstractions";
import {
  SynthesisResultSchema,
  type DimensionMeta,
  type QualityReview,
  type SynthesisResult,
} from "./schemas";
// ★ 直接复用 Apr 21 baseline 的 SOTA REPORT_SYNTHESIS_SYSTEM_PROMPT
import { REPORT_SYNTHESIS_SYSTEM_PROMPT } from "@/modules/ai-app/topic-insights/prompts/report-synthesis.prompt";

export interface SynthesizerInput {
  readonly missionId: string;
  readonly topicId: string;
  readonly topicName: string;
  readonly dimensionMetas: ReadonlyArray<DimensionMeta>;
  readonly integratedSectionsPerDim: Record<string, string>;
  readonly overallReview?: QualityReview;
  readonly userPrompt?: string;
  readonly language: string;
}

export const SYNTHESIZER_SPEC: IAgentSpec<SynthesizerInput, SynthesisResult> = {
  identity: {
    role: {
      id: "AG-11-SY",
      name: "Report Synthesizer",
      description: "从 dimension metas 合成最终 mission 报告。",
      workStyle: "structured",
    },
    persona: { tone: "formal", language: "zh-CN", style: "首席研究编辑" },
    goal: {
      summary:
        "产出 SynthesisResult（executiveSummary + fullMarkdown + highlights + riskMatrix）",
    },
    constraints: {
      maxIterations: 4,
      maxTokens: 80_000,
      maxWallTimeMs: 240_000,
      safetyLevel: "standard",
    },
    tools: ["rag-search", "TL-04-DIMMEM"],
    forbiddenTools: ["TL-02-EVSAVE"],
  },
  taskProfile: { creativity: "medium", outputLength: "extended" },
  outputSchema: SynthesisResultSchema,

  buildSystemPrompt: () =>
    [
      // ★ 直接复用 Apr 21 baseline 的 SOTA REPORT_SYNTHESIS_SYSTEM_PROMPT 原文
      REPORT_SYNTHESIS_SYSTEM_PROMPT,
      "",
      "## 【关键覆盖】输出格式说明（本次调用覆盖 baseline 输出）",
      "本次调用要求输出**纯 JSON 对象**，字段如下：",
      "```json",
      "{",
      '  "missionId": "复制 input.missionId 原值",',
      '  "executiveSummary": "100-4000 字执行摘要",',
      '  "preface": "≥50 字的报告前言",',
      '  "fullMarkdown": "≥500 字完整 markdown 报告",',
      '  "highlights": [                // ≥3 条',
      "    {",
      '      "type": "KEY_FINDING",       // 固定字面量',
      '      "text": "≥10 字的核心发现"',
      "    }",
      "  ],",
      '  "crossDimensionAnalysis": "≥50 字跨维度因果分析",',
      '  "riskMatrix": [                 // ≥1 条',
      "    {",
      '      "level": "high",              // enum: high | medium | low',
      '      "description": "≥10 字风险描述",',
      '      "relatedDimensions": ["dim-id-1"]',
      "    }",
      "  ],",
      '  "recommendations": [            // ≥1 条',
      "    {",
      '      "priority": "P0",             // enum: P0 | P1 | P2',
      '      "action": "≥10 字具体行动",',
      '      "rationale": "≥10 字理由",',
      '      "relatedDimensions": ["dim-id-1"]  // ≥1 条',
      "    }",
      "  ]",
      "}",
      "```",
      "",
      "⚠️ 严厉约束：严禁重写 dimension 正文；严禁新增来源；严禁臆造数据；数字是数字不是字符串；严格 JSON；不输出 ```json 外层 fence。",
    ].join("\n"),

  buildUserPrompt: (ctx) => {
    const { input } = ctx;
    return [
      `missionId: ${input.missionId}`,
      `topic: ${input.topicName}（id=${input.topicId}）`,
      `language: ${input.language}`,
      input.userPrompt ? `userPrompt: ${input.userPrompt}` : "",
      "",
      "dimensionMetas:",
      ...input.dimensionMetas.map(
        (m) =>
          `  - ${m.dimensionName}\n    summary: ${m.summary}\n    keyFindings: ${m.keyFindings.join(" | ")}\n    evidenceCount: ${m.evidenceCount}`,
      ),
      "",
      input.overallReview
        ? `overallReview score: ${input.overallReview.overallScore}`
        : "",
      "",
      "请输出 SynthesisResult JSON。",
    ]
      .filter(Boolean)
      .join("\n");
  },

  stubFn: async (ctx) => {
    const { input } = ctx;
    const execSummary =
      `# 执行摘要\n\n本报告就 ${input.topicName} 从 ${input.dimensionMetas.length} 个维度展开系统研究。` +
      input.dimensionMetas
        .map((m) => `\n\n**${m.dimensionName}**：${m.summary.slice(0, 200)}...`)
        .join("") +
      "\n\n综合分析表明：上述研究具有结构性机会与阶段性风险并存的特征。（stub synthesis）";

    const fullMarkdown =
      `# ${input.topicName} · 综合研究报告\n\n` +
      execSummary +
      "\n\n" +
      input.dimensionMetas
        .map(
          (m, idx) =>
            `## ${idx + 1}. ${m.dimensionName}\n\n${m.summary}\n\n` +
            m.keyFindings
              .slice(0, 3)
              .map((kf, i) => `- 发现 ${i + 1}：${kf}`)
              .join("\n"),
        )
        .join("\n\n") +
      "\n\n## 结论\n\n" +
      `综合以上 ${input.dimensionMetas.length} 个维度分析，${input.topicName} 的演进呈现复合型趋势（stub）。` +
      "（stub：核心观察包括各维度间存在系统性关联、风险与机会并存。）" +
      `\n\n> Generated by harness mission ${input.missionId}`;

    const highlights = input.dimensionMetas.slice(0, 5).map((m, idx) => ({
      type: "KEY_FINDING" as const,
      text: `${m.dimensionName}：核心发现 ${idx + 1}（${m.keyFindings[0] ?? ""}）`,
    }));

    return {
      missionId: input.missionId,
      executiveSummary: execSummary.slice(0, 3500),
      preface: `本报告针对 ${input.topicName} 进行深度研究（stub preface ≥50 字）。使用 ${input.dimensionMetas.length} 个分析维度，综合得出结论与建议。`,
      fullMarkdown,
      highlights:
        highlights.length >= 3
          ? highlights
          : [
              ...highlights,
              ...Array.from({ length: 3 - highlights.length }).map((_, i) => ({
                type: "KEY_FINDING" as const,
                text: `补齐 stub highlight ${i + 1}（stub）`,
              })),
            ],
      crossDimensionAnalysis:
        `跨维度分析：${input.dimensionMetas.map((m) => m.dimensionName).join("、")} 之间形成互补与制约关系，` +
        "其中趋势层面的共振、挑战层面的叠加、机会层面的互补三条主线清晰可见（stub cross-dimension analysis）。",
      riskMatrix: [
        {
          level: "medium" as const,
          description: "stub: 数据时效性风险",
          relatedDimensions: input.dimensionMetas
            .slice(0, 2)
            .map((m) => m.dimensionId),
        },
      ],
      recommendations: [
        {
          priority: "P1" as const,
          action: `针对 ${input.topicName} 补充更多时效数据`,
          rationale: "避免数据过期带来的结论偏差",
          relatedDimensions:
            input.dimensionMetas.length > 0
              ? [input.dimensionMetas[0].dimensionId]
              : ["stub-dim-1"],
        },
      ],
    };
  },
};
