import type { ExitDecision, TopicType } from "../evaluation";

export type { TopicType };

export interface IterationRecord {
  round: number; // 0 = init, 1+ = iterations
  type: "init" | "iteration" | "summary";
  markdown: string;

  research: {
    queries: string[];
    newSources: number;
    totalSources: number;
    informationGain: number;
  };
  ideas: {
    newInsights: string[];
    newCreativeIdeas: string[];
    totalInsights: number;
    totalCreativeIdeas: number;
    adoptedInDemo: string[];
  };
  demo: {
    score: number;
    changes: string[];
    topicType: string;
  };

  gaps: {
    dataGaps: string[];
    ideaGaps: string[];
  };

  exitDecision: ExitDecision;
  timestamp: Date;
}

export interface IdeaSummary {
  id: string;
  title: string;
  type: "INSIGHT" | "CREATIVE_IDEA";
  sourceRound: number;
  adoptedInDemo: boolean;
}

export interface StartIterativeResearchDto {
  query: string;
  mode: "single" | "iterative";
  options?: {
    maxRounds?: number;
    includeAcademic?: boolean;
    language?: string;
    depth?: "quick" | "standard" | "thorough";
  };
  iterationOptions?: {
    maxIterations?: number;
    qualityThreshold?: number;
    autoGenerateDemo?: boolean;
  };
  isFollowUp?: boolean;
  previousContext?: {
    executiveSummary: string;
    sections: { title: string; content: string }[];
    conclusion: string;
    references: { title: string; url: string }[];
  };
}

// SSE event types

export interface IterationStartEvent {
  type: "iteration.start";
  data: {
    round: number;
    targetGaps: { dataGaps: string[]; ideaGaps: string[] };
  };
}

export interface IterationResearchEvent {
  type: "iteration.research";
  data: {
    round: number;
    queries: string[];
    newSources: number;
    informationGain: number;
  };
}

export interface IterationIdeasEvent {
  type: "iteration.ideas";
  data: {
    round: number;
    newInsights: Array<{ title: string }>;
    newCreativeIdeas: Array<{ title: string }>;
    totalInsights: number;
    totalCreativeIdeas: number;
  };
}

export interface IterationDemoEvent {
  type: "iteration.demo";
  data: { round: number; status: "generating" | "completed" };
}

export interface IterationEvalEvent {
  type: "iteration.eval";
  data: {
    round: number;
    score: number;
    previousScore: number;
    gaps: { dataGaps: string[]; ideaGaps: string[] };
  };
}

export interface IterationExitEvent {
  type: "iteration.exit";
  data: { reason: string; finalScore: number; totalIterations: number };
}
